### ISSUE TITLE
[BUG] QuotaExceeded

### ISSUE THREAD

**Issue by NoraYan** [amzn/selling-partner-api-models#1176]
we are trying to get orders, each order items, buyer info and address info via Api. There is no single api to get all the info , so we need to call different api by looping orders. Then we got error below: 
429 {
  "errors": [
    {
      "message": "You exceeded your quota for the requested resource.",
     "code": "QuotaExceeded"
    }
How to solve this issue?

**Comment by fret423** [comment]
Thanks for your thoughts @ivanzonware. While your first 2 suggestions completely make sense, waiting for 12/24 hrs in many scenarios just isn't possible. A whole lot of use-cases of the API require 10s to 100s of API calls/day which definitely can't be deferred by 12/24 hrs. 

I hope your tagged @parvathm can lend some more insights to this.

**Comment by pauljones0** [comment]
Commenting to keep the topic alive. I was planning on building a price tracking based on the SP-API, but now it seems that this is a terrible way to do so.

**Comment by or-en** [comment]
Did anyone find solution or explanation for this issue?

**Comment by SuperFlyingCow** [comment]
Experiencing this often now to almost all of the SP APIs. Anyone was able to fix it?

**Comment by luap2703** [comment]
> @jordantomax same issues here, using https://github.com/saleweaver/python-amazon-sp-api which is also endowed with the decorator throttle_retry(exception_classes=(), tries=5, delay=200, rate=1.3)
> 
> but after downloading a good amount of reports, the calls start to fail with the error {'code': 'QuotaExceeded', 'message': 'You exceeded your quota for the requested resource.', 'details': ''} and do not resume to normal operations unless waiting several hours.
> 
> I am using the Create Report operation https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#post-reports2021-06-30reports
> 
> which has the following rate limits
> 
> Rate (requests per second)	Burst
> 0.0167	15
> I suspect issues at Amazon SP-API side
> 
> I tag @parvathm from SP-API support to have more attention on the issue and to provide a viable workaround
> 
> edit
> 
> ### POSSIBLE WORKAROUND
> I noticed that the number of reports allowed before running into the QuotaExceeded is very close to the Create Report Burst. This lead me to believe that SP-API is changing the Rate and Burst dynamically without telling us due to overload on their side or similar issue. (example below) ![Screen Shot 2024-03-25 at 22 09 38](https://private-user-images.githubusercontent.com/99758179/316947659-515f44c7-2f63-4e67-858f-9974630a94e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMzczMzcsIm5iZiI6MTczMjIzNzAzNywicGF0aCI6Ii85OTc1ODE3OS8zMTY5NDc2NTktNTE1ZjQ0YzctMmY2My00ZTY3LTg1OGYtOTk3NDYzMGE5NGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAwNTcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZTlmZDgwMDJlMzc0ZDAwMGQ3MmRmOThjY2E2ZWY2MWUyMGY1OWViNWQ3YmJkMGJlNzAyOWE3ZTVkMDkwYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EhkhVZtU5pnfMolfm-W0LVyLPwXyS2fRk8fTlrHEx_A) and later we get QuotaExceeded
> 
> Strategy:
> 
> 1. save on the number of calls -> use maximum date range possible for your use case. In this way instead of making 12 calls for 30days report, you can make 1 call for 360days period.
>    Make sure you can handle properly loading data (DB, memory ...)
> 2. introduce delay/sleep between one call and another, as a safety measure do not rely on Burst and always stay below the Rate for the given operation
> 3. once you hit QuotaExceeded wait for 12/24 hrs to allow the situation to reset

Welcome to christmas 2024 and these errors occur for all our sellers regularly per day. To add onto this, using 1 report for 360d is not even possible for most reports.

We're ending up in not reliably being able to synchronize with reports.

I hope the amazon dev team is aware of the horrible experience that they do offer to their service providers and merchants..., never had so much pain with any API.

**Comment by luckdragon** [comment]
personally, I don't understand the whole rate/burst thing, I mean one of the apis has a rate of 2, but a burst of 6, when it gives me quota exceeded, how can I calculate the wait time?

**Comment by SuperFlyingCow** [comment]
> personally, I don't understand the whole rate/burst thing, I mean one of the apis has a rate of 2, but a burst of 6, when it gives me quota exceeded, how can I calculate the wait time?

From what I understand, if the rate = 2/second this means that you are allowed to call the API 2 times in a second. The burst is the number of parallel requests the amazon internal processing bucket allows. This means that that the processing bucket can only hold up to 6 API request. So for example, you call 2 API request in a second, this 2 will be added in the bucket. While the requests are being processed in the bucket and then you add 2 again after one second, we now have 4 requests in the bucket. If the 4 did not finish yet, and you add 2 again after one second (because we are allowed to do so based from the rate limit), you will now have 6 requests in the bucket. And if you call again the same API, it will be throttled, because you already have 6 requests in the bucket. Aside from the 1 second rate, you also need to know how many seconds/minutes one API call finishes, so as not to accumulate all the requests in the bucket causing quota exceeded as well.

**Comment by luckdragon** [comment]
that is what I understand also, which is why the fact that sometimes there are periods of 10-15 minutes between runs and I still get the over quota error.. and I know that the execution is complete, because I can't move onto the next step without it completing is so confusing

**Comment by chris-skuvault** [comment]
I have issues with this as well. 

Everything I can tell is setup correctly to properly rate limit and back off the appropriate amount. 

I have a .net implementation and am using Polly for the rate limiting functionality. I handle the potential dynamic nature of the rate by storing and checking the `x-amzn-RateLimit-Limit` header when its returned in a success call.

For the https://developer-docs.amazon.com/sp-api/docs/finances-api-reference#get-financesv0financialevents endpoint I get frequent 429's even after waiting the appropriate time. 

For instance I'm having issues where I send a request for the endpoint and get a 200 back. A few hours later I send another request and get 429 back. I then delay a bit more than 2 seconds and retry. I do this because of the 0.5 rate which means I should be able to make a request every 2 seconds without getting throttled. This frequently fails with 429. I'm not doing things asynchronously so for a given tenant I should be respecting the rate and burst limits.

In my logs I can see based on timestamps that I sometimes get throttled every try until it gives up. Then a bit later an hour or more it might succeed or might fail initially and then succeed. The rate limiting seems pretty flaky and doesn't seem to work as the documentation indicates.

Not sure what else I can do besides add more retries with longer delays. There doesn't seem to be a well documented approach for how this should work and its hard to understand when things aren't working.

**Comment by saeedasma** [comment]
Hello all, 

Did you find a solution to this issue? I am calling ListFinancialEvents and getting Quota Exceeded error. I am just making one api call ListFinancialEvents(which returns the data for a date range) after every 10 minutes. I also tried to increase the time to 1 hour instead of 10 minutes but still getting the same error. 

Thanks,
Asma
