### ISSUE TITLE
Feauture Request: Update Price and Stock

### ISSUE THREAD

**Issue by mike59999** [amzn/selling-partner-api-models#12]
Hello,

will it be possible in the future to update the price and stock over the API directly or are feeds always needed?

best regards,

Michael

**Comment by jaypiix3** [comment]
Hello, 

i'd also like to have such a feature for sp-api.

Kind regards.

**Comment by seanevan** [comment]
Hi @mike59999 and @jaypiix3, at this time Feeds are needed for those types of operations. Could you please expand on your use cases to help me understand where dedicated APIs would better enable them?

Thanks,
Sean Evans
Manager, Support Engineering

**Comment by manishjha01** [comment]
We also need this feature. 
Use-case: Our merchant clients manage physical product inventory in local networked system that we need to publish accurate stock and price changes to Amazon. In other words, need an easy way to send price and quantity stock updates to a list of products on Amazon.

**Comment by ericblade** [comment]
Aye. generating feeds for small item updates is really quite a hassle, and is part of what CRUD interfaces such as this new API are usually designed for.  Feeds aren't exactly the best interface for really much of anything, unless you're doing massive amounts of updates/changes/replacements in a database, Having some easy to use POST/PUT/PATCH functionalities available for many of the common operations, would be really, really nice.  Throttle them appropriately if necessary, and large operations can be done via feeds directly, if that's necessary.. but overall, feeds were a system designed approaching 20 years ago, that probably aren't used by a lot of sellers, because they're just too much of an annoyance.  For any small numbers of operations, when possible, it's easier to just go in through sellercentral to list a single item or to change a price.. but it would be *really* great if we could easily provide new interfaces for individiual operations, without having to figure out how to generate a feed file that fits the current standard, figure out what feed format is required for the specific operation/product, wait minutes for the feed to be processed, and then query a response for it, then if it failed, query a report, to find out why it failed, and figure out how to explain that to the user.

I'd honestly say, that any operation people are routinely doing via SellerCentral or the mobile SellerCentral app, that requires a feed to do normally, would be a great candidate for adding capability to the new API.
