### ISSUE TITLE
Vendor Central SP-API -  Carton labels for Retail Procurement?

### ISSUE THREAD

**Issue by gabeo671** [amzn/selling-partner-api-models#1312]
Is there a way to generate labels for Retail Procurement shipments or are they only available for Direct Fulfillment?

**Comment by Xriuk** [comment]
Carton and pallet labels need to be created manually by providing your own SSCC number during creation. I don't know how to create ASN labels tho, since it seems that you cannot retrieve the submitted shipping confirmations for Prepaid/TheyPay orders, and thus cannot retrieve the generated ASN number.
