### ISSUE TITLE
/ Forward Slash in URI does not work in supplied client in dotnet

### ISSUE THREAD

**Issue by kpconnell** [amzn/selling-partner-api-models#208]
I am still trying to find a solution for how to encode and sign requests when the URI element contains a slash.

so for example:
POST
/products/fees/v0/listings/{sku}/feesEstimate

if {sku} = “mysku/withaslash”…

The supplied dotnet swagger client does not work

what is the second line of the canonical string to sign you to send?
What is the actual query string passed to the REST call.
I have tried every combination of encoding I can think of without any love.

**Comment by shreeharsh-a** [comment]
Hi,
Please be advised that the schema / type for the SKU is of type string. Using any form of encoding etc may / may not work or may cause unintentional behaviours so please ensure to fully test including checking API responses etc as that may use the encoding as part of data / value & thus may call for additional code to handle such encodings etc in your app.

You can try using:

`%252F`

in place of the slash i.e. '/'

So in your e.g. {sku} = "mysku%252Fwithaslash"

Again, please ensure to handle such encodings etc if the SKU itself is stored with this encoding.

Alternatively, you can refactor to use a dash i.e. '-' instead of a '/' or any other character instead of '/'.
