### ISSUE TITLE
OpenAPI Generator fails on catalogItems_2020-12-01.json fails

### ISSUE THREAD

**Issue by alexluca89** [amzn/selling-partner-api-models#213]
When I used OpenAPI Generator on catalogItemsV0.json it worked just fine. Unfortunately it doesn't work for the new version.

![image](https://user-images.githubusercontent.com/37292947/152005983-58187738-7e8d-4212-8abf-a21575c0dbb8.png)

**Comment by chapmanjw** [comment]
Hello @alexluca89,

I see the cause of the issue in the model being that the `default` for the `includedData` query parameters is a string instead of an array of strings. I will work with our content team on getting that model fixed. 

In the meantime, this does not impact the Swagger 2.0 codegen utility. To unblock your integration, I would suggest either using that or simply removing `"default": "summaries"` from the model before running the OpenAPI Generator.

Thanks!
