### ISSUE TITLE
IsBuyBoxWinner returns incorrect data in both GetListingOffers and ANY_OFFER_CHANGED 

### ISSUE THREAD

**Issue by igoryan-k** [amzn/selling-partner-api-models#2130]
Hello, I am getting issues with determining the buy box winner using the SP API.

GetListingOffers documentation says that IsBuyBoxWinner could be True for up to two offers (1 FBM and 1 FBA), but I found that it doesn’t guarantee that some other offer is an actual buy box winner.

Here is an example that I am observing. I receive a list of 20 offers with the top 4:

71.39 FBM - IsBuyBoxWinner = False
71.50 FBM- IsBuyBoxWinner = True
73.00 FBA - IsBuyBoxWinner = True
**74.63 FBA - IsBuyBoxWinner = False**
…

The actual winner is offer 4 - $74.63, even though offer 3 is marked with IsBuyBoxWinner = True.

GetCompetitivePricing() returns offer 2 as BuyBoxPrices.

I am seeing the exact same data via the ANY_OFFER_CHANGED feed for this ASIN.

Is this a known issue?

**Comment by asafpol** [comment]
I'm not sure why this issue was closed - the behavior described in this thread matches exactly what I see in my implementations. The buybox is just off - I tried many zipcodes and it doesn't impact. I tried looking at both prime and non-prime buyers - doesn't matter.

This is fairly basic need for a seller to know what the REAL buybox is - someone should fix this.
