### ISSUE TITLE
Merchant Fulfilment: Specifying a label format fails with valid parameters

### ISSUE THREAD

**Issue by elliottwood80** [amzn/selling-partner-api-models#214]
Hi, I'm using the merchant fulfilment api and calling the createshipment end point, if I specify a label type, regardless of the type (PDF, PNG, ZPL203) I'm always getting the following error:

_The selected delivery method does not offer the requested label format. Please choose a different label format or choose another delivery method which offers the requested label format_

Even if I check the eligible types for the selected service and select one that matches, I still get the error. 

However if if I do not specify any label type, it's then successful and I get back a PDF label. 

Is there a bug with the API not handling the label types properly

**Comment by elliottwood80** [comment]
Has anyone else tried this and had any success?

**Comment by franciscocha** [comment]
@elliottwood80 we are still in the middle of development and are running into issues with the sandbox requests. But are you testing this in production or sandbox?

**Comment by elliottwood80** [comment]
Hi, we're getting the issue in production.

**Comment by Adrian-T-AMZN** [comment]
Hello @[elliottwood80](https://github.com/elliottwood80),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
