### ISSUE TITLE
[BUG]CAN NOT deleteSubscriptionById on notificationType:ORDER_STATUS_CHANGE

### ISSUE THREAD

**Issue by guoliesheng** [amzn/selling-partner-api-models#227]
When call deleteSubscriptionById that want to delete a ORDER_STATUS_CHANGE Subscription, the api response
 {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}.
But I can delete other type Subscription

**Comment by Adrian-T-AMZN** [comment]
Hello @[guoliesheng](https://github.com/guoliesheng),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
