### ISSUE TITLE
No buyer-tax-registration-id in FBA Invoicing Report

### ISSUE THREAD

**Issue by conglun** [amzn/selling-partner-api-models#229]
There is no buyer-tax-registration-id field returned in Report GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING, when using RDT token.

However, we can find buyer-tax-registration-id field in Report GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING.

How to get FBA order's buyer invoicing information?

**Comment by Adrian-T-AMZN** [comment]
Hello @[conglun](https://github.com/conglun),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
