### ISSUE TITLE
report GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE gets cancelled all the time

### ISSUE THREAD

**Issue by Javadebi** [amzn/selling-partner-api-models#2292]
I want to create a report with GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE type and everytime I request It gets cancelled.
Why is that????
Any reason? 
At least give proper error

**Comment by GravesendNeckRoad** [comment]
I noticed that this issue is still affecting users, so I wanted to chime in (this thread is the first result in search engines).

`GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE ` is for **FBM/MFN** returns data.
`GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA` is for **FBA/AFN** returns data.

The SP-API returns "Cancelled" for any reports containing no data. Thus, if you're exclusively an FBA seller and unknowingly request the FBM report, it will throw you a "Cancelled", since you have no FBM sales. Instead, you should call the FBA/AFN report.

I believe the issue lies in the naming: `GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE` is ambiguous and could apply to either FBA or FBM.

Likewise, `GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA` is _not_ listed under "Returns Reports" in the developer docs. Instead, it's categorized as "FBA Concessions Reports" under "Fulfillment by Amazon (FBA) Reports", which probably causes some to overlook it. Compare this with the orders report, `GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL`, which is listed under both "Fulfillment by Amazon (FBA) Reports" _and_ "Order Reports," ensuring it wont be missed. 

At least, this is the mistake I was making. Hope this helps.

**Comment by romanstingler** [comment]
AMZ is just..... 

`GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA`
gives me

```
{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to the resource is forbidden",
            "details": ""
        }
    ]
}
```


`GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE`
gives me a file in the end but the file is empty when I know for sure that there are returns

**Comment by johnkw** [comment]
This is a duplicate of bug #393 (which is still a critical bug and should be reopened instead of being moved to a discussion).

**Comment by sany2k8** [comment]
> I noticed that this issue is still affecting users, so I wanted to chime in (this thread is the first result in search engines).
> 
> `GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE ` is for **FBM/MFN** returns data. `GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA` is for **FBA/AFN** returns data.
> 
> The SP-API returns "Cancelled" for any reports containing no data. Thus, if you're exclusively an FBA seller and unknowingly request the FBM report, it will throw you a "Cancelled", since you have no FBM sales. Instead, you should call the FBA/AFN report.
> 
> I believe the issue lies in the naming: `GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE` is ambiguous and could apply to either FBA or FBM.
> 
> Likewise, `GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA` is _not_ listed under "Returns Reports" in the developer docs. Instead, it's categorized as "FBA Concessions Reports" under "Fulfillment by Amazon (FBA) Reports", which probably causes some to overlook it. Compare this with the orders report, `GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL`, which is listed under both "Fulfillment by Amazon (FBA) Reports" _and_ "Order Reports," ensuring it wont be missed.
> 
> At least, this is the mistake I was making. Hope this helps.

You are awesome. I was scratching my head for this issue and finally your comment fixed it. Thanks again.

**Comment by johnkw** [comment]
This is a duplicate of bug https://github.com/amzn/selling-partner-api-models/issues/393 (which is still a critical bug and should be reopened instead of being moved to a discussion).
