### ISSUE TITLE
[BUG] Missing BuyerTaxInfo | Order -> BuyerInfo -> BuyerTaxInfo is null

### ISSUE THREAD

**Issue by kevinvenclovas** [amzn/selling-partner-api-models#235]
Hi,

the api work very well but i have one question every time i requested an order the "BuyerTaxInfo" is null. With the old MWS-Api i get all this informations.

I already use the RestrictedResource to request the "buyerInfo", "shippingAddress" but this information always remain null.

So how can i get the "BuyerTaxInfo"? Is there n extra function to request thsi information?

Maybe ther is a simple solution. Someone have an idea?

![image](https://user-images.githubusercontent.com/7681603/161209747-c0645168-ad97-4a6b-a1f6-f1deb24d1ff8.png)

BuyerTaxInfo is still missing in the response payload.

**Comment by franciscocha** [comment]
Is you order from the TR Marketplace? As stated in the documentation this information is only available for the TR Marketplace. https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#buyertaxinformation

**Comment by kevinvenclovas** [comment]
No, order is from germany . But why is this important information only available in TR? -.-

**Comment by Adrian-T-AMZN** [comment]
Hello @[kevinvenclovas](https://github.com/kevinvenclovas),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
