### ISSUE TITLE
[BUG] FBA Inventory APIs often fail while generation

### ISSUE THREAD

**Issue by nguyentoanit** [amzn/selling-partner-api-models#2388]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
Inventory APIs rarely generate report successfully in EU region.
Use same parameters:

```json
{
    "marketplaceIds": [
        "A1PA6795UKMFR9"
    ],
    "reportType": "GET_AFN_INVENTORY_DATA"
}
```

Report API v2021-06-30 often retrieved `"processingStatus": "FATAL"` when generation.

Here is report response which I got from [getReport](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#getreport) API:

```json
{
    "reportType": "GET_AFN_INVENTORY_DATA",
    "processingEndTime": "2022-04-26T10:00:07+00:00",
    "processingStatus": "FATAL",
    "marketplaceIds": [
        "A1PA6795UKMFR9"
    ],
    "reportId": "REPORT_ID",
    "dataEndTime": "2022-04-26T09:59:53+00:00",
    "createdTime": "2022-04-26T09:59:53+00:00",
    "processingStartTime": "2022-04-26T09:59:58+00:00",
    "dataStartTime": "2022-04-26T09:59:53+00:00"
}
```

**URL of the content on GitHub**
N/A

**Description of what the documentation currently says**
https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference

**Description of what the documentation should say**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by idmacommerce** [comment]
Issue still there in 2024

**Comment by ManuMalempati** [comment]
Hi, I am facing same issue in 2026. I am trying to access the report version "GET_AFN_INVENTORY_DATA" since the get inventory summaries API is not generating the summaries correctly in EU region. It gives me FATAL error when trying to access the report, but if i try after 20 or so minutes it allows me to access it. Not sure why it has such strict rate limits. This is very difficult for me to work with when testing my code. I checked the rate limits for get report API which allows 2 requests persecond and burst of 15, so im not sure why i am only able to access report every 20 minutes. Please help.

Thanks
