### ISSUE TITLE
[BUG] [SP-API] [Issue] estimateTransport returns 412

### ISSUE THREAD

**Issue by defenderjim** [amzn/selling-partner-api-models#2486]
<pre><code>
[X] Bug report  
</code></pre>
estimateTransport returns error 412,
```

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "FTXGatewayService.estimateLtlShipment returned error code: 412",
      "details": ""
    }
  ]
}

```

## SP-API Name and Version or Report/Feed Type
POST to fba/inbound/v0/shipments/FBAxxxxxx/transport/estimate

## Expected Behavior

Should get  "EstimateTransportResponse"

The response I get is: "FTXGatewayService.estimateLtlShipment returned error code: 412"
There is no documentation on what this means.  The response does not indicate what is causing this problem.

## Current Behavior

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "FTXGatewayService.estimateLtlShipment returned error code: 412",
      "details": ""
    }
  ]
}

A detailed error message would really help.  An explanation of what is causing error 412 and how the issue is w/the request.

## Context/Screenshots

Trying to purchase LTL Partnered shipping.

**Comment by johnkw** [comment]
Thanks so much for posting this critical bug report! We hit this due "IsStacked" being set to true for a pallet over 50 inches tall. That's not exactly the same as above, but your report helped me to look in the right direction.

Since this is still an active open bug @shreeharsh-a can you reopen, or move it to a discussion if that's where active open bug reports go now?
