### ISSUE TITLE
[BUG] [SP-API] [Issue] InvalidInput - Invalid request parameters

### ISSUE THREAD

**Issue by amazing-user** [amzn/selling-partner-api-models#2549]
Getting an error when trying to retrieve the error of the uploaded feed using the create feed, Feed Type: POST_PRODUCT_DATA
 
## SP-API Name and Version or Report/Feed Type
POST_PRODUCT_DATA v2021-06-30

I am following the step 4 in
https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#step-4-create-a-feed

API: /feeds/2021-06-30/feeds

getting below response:
    Response:
    {
      "errors": [
        {
          "code": "InvalidInput",
          "message": "Invalid request parameters",
          "details": ""
        }
      ]
    }
 
It was working 6 months ago but not working now. Seems something has changed.

**Comment by Gijsvs** [comment]
I'm experiencing this error as well in our system and have not yet found the root cause, luckily I can already answer the question asked by @albinsopaj. In the request `marketplaceIds` actually needs to be a list of entries and not a string. So your requests should look like:

```diff
{
-    "marketplaceIds" : "APJ6JRA9NG5V4",
+    "marketplaceIds" : ["APJ6JRA9NG5V4"],
    "feedType" : "POST_FLAT_FILE_INVLOADER_DATA",
    "inputFeedDocumentId" : "amzn1.tortuga.4.eu.ca73b145-9e7c-4d38-872d-42360ddf5a44.TKFQ2AIVLHF2U"
}
```

> It would have been great if it would have shown message like "Account disabled" rather than "InvalidInput".

I fully agree with this point, it would be great to know why the input was rejected if the error is not due invalid input data but instead some constraint imposed on the Amazon Account which is not visible in the API (i.e. through the participation endpoint). Now I have a hard time building correct error handling for this.
