### ISSUE TITLE
Query-parameter identifiersType does not have the expected effect on the result

### ISSUE THREAD

**Issue by Schubi1981** [amzn/selling-partner-api-models#264]
When making a call to /catalog/2022-04-01/items?marketplaceIds=A1PA6795UKMFR9&identifiers=841667189314&identifiersType=EAN&includedData=identifiers we get a result, although the given identifier is not the EAN (even not a valid EAN) but the UPC. Same if we request the data with identifiers=0841667189314&identifiersType=UPC (the given identifier is an EAN and not a UPC). We also had some examples where we requested data by an EAN and got a result but that EAN does not appear in the returned identifiers. Instead it contained a GTIN which value was the requested EAN with a leading zero. Is this a bug or a feature? When we are making a request with multiple identifiers, we try to match the requested ids with the returned ones to see if we got for any requested identifier no result. This would be a little bit trickier, if we get some results, whose identifiers do not contain the actually requested ones.

**Comment by chapmanjw** [comment]
@Schubi1981 Currently, all GTIN-compatible identifiers are converted to GTINs (as our index is GTIN-based). However, as you are seeing, the value on the ASIN may actually be an EAN, UPC, etc., rather than the GTIN itself. 

As the results are showing what is actually on the ASIN, what would be your preferred behavior here? Should the API reject invalid EANs when the input is a UPC? Or would appending the input identifier (when not on the ASIN) into the identifiers response be preferable (which could cause confusion in other areas if its only there when queried by the identifier and not when retrieved by ASIN, etc.)?

**Comment by Schubi1981** [comment]
For our usecase the current behaviour is okay. It is only important to know, if this is a bug or a feature. If this behaviour changes, some of our logic wouldn't work anymore.
