### ISSUE TITLE
[BUG] [SP-API] [Issue] Unable to get BuyerCustomizedInfo details

### ISSUE THREAD

**Issue by git-chintan-dave** [amzn/selling-partner-api-models#2690]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
`/orders/v0/orders/:orderId/orderItems/buyerInfo`

## Expected Behavior
I should be able to retrieve the order item customization info

## Current Behavior
Not able to fetch the order item customization info from `/orders/v0/orders/:orderId/orderItems/buyerInfo`

## Context/Screenshots
![image](https://github.com/amzn/selling-partner-api-docs/assets/26324837/9f119235-2619-4eb7-bdd8-ce58f26181e7)

## Your Environment
Postman - `/orders/v0/orders/:orderId/orderItems/buyerInfo`

**Comment by tspicer** [comment]
this issue still exists

**Comment by jjuelotc** [comment]
@tspicer I eventually found out why it was happening the way it was. It is because that data could contain PII so it gets protected behind an RDT.

You will need set up your code to work with multiple tokens. Your regular token will be used for most calls. Then you need one or more RDTs where you have specified the specific data objects you need access to. 

In my use case I found there were two types of RDTs to generate with calls to /tokens/2021-03-01/restrictedDataToken to get the token used on calls to the paths listed below.

First is a call to the orders endpoint to get orders with the address object populated.

```
{
  "restrictedResources": [
    {
      "method": "GET",
      "path": "/orders/v0/orders",
      "dataElements": ["buyerInfo", "shippingAddress"]
    }
  ]
}
```

Second is a call to orderItems to get the item level data with the additional buyer info that contains customization.

```
{
  "restrictedResources": [
    {
      "method": "GET",
      "path": "/orders/v0/orders/{orderId}/orderItems",
      "dataElements": ["buyerInfo"]
    }
  ]
}
```

Note: I have not implemented this in our deployed workflow but if I recall from my POC I worked up 6 month ago, all the info I needed was in these two calls if the correct RDTs were used. Also, the RDT as a 3600 second expiration so it can be reused for repeated calls such as getting 100 orders and then calling for orderItems 100 times.
