### ISSUE TITLE
Missing AWSAuthenticationCredentialsProvider

### ISSUE THREAD

**Issue by mravoni** [amzn/selling-partner-api-models#27]
Reading the Selling Partner API Developer Guide I know that you need to sign your request to make it.
I did it using self authorization, but everytime I try to make a call I receive this answer:
  "errors": [
   {
     "message": "Access to requested resource is denied.",
    "code": "Unauthorized",
    "details": ""
   }
 ]

I saw that if you make a request using c# library AWSAuthenticationCredentialsProvider sign is missing.
Is it the reason why I can't do any operation? Is because I can't assign a role session as you can do using the AWSAuthenticationCredentialsProvider in Java?

**Comment by tenitre** [comment]
@mravoni follow the steps I explained here
https://github.com/amzn/selling-partner-api-models/issues/31

it has your missing step too.. search for this "Note2: The Amazon documents are missing (surprised, surprised) steps. This AssumeRole call is very important otherwise you will keep getting Forbidden" 

and good luck

**Comment by mravoni** [comment]
Finaly it works!! Thank you so much!!!

**Comment by tenitre** [comment]
> Finaly it works!! Thank you so much!!!

NP... Glad to hear that it works for you too..
