### ISSUE TITLE
Retrieve Merchant Shipping Templates using the Product Type Definitions API

### ISSUE THREAD

**Issue by xuepengwei** [amzn/selling-partner-api-models#2799]
I went through [this article](https://developer-docs.amazon.com/sp-api-blog/docs/etrieve-merchant-shipping-templates-using-the-product-type-definitions-api) tried Retrieve Merchant Shipping Templates, but in actual operation, the fourth step did not obtain the content introduced in the article

![image](https://github.com/amzn/selling-partner-api-docs/assets/24579048/5b002f6e-51fd-461e-9018-cd79d93e3a7e)

**Comment by leonardonakagawa** [comment]
Hi @xuepengwei,

This might be caused by the Seller ID not being passed in the getDefinitions Product Type API call.

Please take a look at the table in the [Step 2](https://developer-docs.amazon.com/sp-api-blog/docs/etrieve-merchant-shipping-templates-using-the-product-type-definitions-api#step-2-set-the-parameters-for-your-api-call-with-the-product-type-definitions-api) to ensure you are doing it correctly.

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by whitedevils** [comment]
I'm in the same situation and i pass correctly the seller ID
