### ISSUE TITLE
[BUG] [SP-API] Missing Date Information for `InboundShipmentInfo` in FULFILLMENT INBOUND API

### ISSUE THREAD

**Issue by ProNotion** [amzn/selling-partner-api-models#2847]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

`InboundShipmentInfo` is missing the shipment created and updated dates. You currently allow for `LastUpdatedBefore` and `LastUpdatedAfter` parameters in the `GET /fba/inbound/v0/shipments` requests but no dates are returned in the response object.

## SP-API Name and Version or Report/Feed Type

Fulfillment Inbound API v0 - getShipments

## Expected Behavior

Currently, there is no useful data returned that allows the date of the shipment to be determined. The response object should include the creation date and the last updated date.

## Current Behavior
No date information is returned.

## Context/Screenshots
We are importing shipments for tracking purposes and are unable to order or query data based on date.

**Comment by emakunin** [comment]
@ProNotion I guess we should re-open a ticket. or tag some Amazon folks here with a hope they'll check. @mafge seems to be the architect for the API as per his signature. (not sure about underlying services)

The V0 api is kinda deprecated so maybe they'll provide some timeline for new functions. Even with the v2024 api it's close to impossible to track the inventory state. Maybe only reports pooling and remembering the state with a timestamp and then querying the first timestamp where new shipment ID appeared =\

It would be super cool to list shipments/items not by "last updated" date but say "shipment created at" or other "stable" fields. Otherwise it's hard to iterage/paginate and relate the data to the reports.

Use case: I want to see where my inventory is/gone for last week. With existing API it's a headache. I try to rely on the reports/ledgers but it's not trivial.

**Comment by ProNotion** [comment]
I don't see any option to reopen it so I think they will need to intervene.

**Comment by mafge** [comment]
Hi @ProNotion and @emakunin,
thanks for notifying me! Let me check how I can help you out here. I'll keep you updated.
Best,
Marc
