### ISSUE TITLE
[FEATURE] Amazon Referral Fee Category

### ISSUE THREAD

**Issue by kennedyjustin** [amzn/selling-partner-api-models#2916]
**Describe the improvement**
Right now it is not documented how an ASIN's fee category can be retrieved from the SP API. Is this just the WebsiteDisplayGroup?

**Description of what the documentation should say**
Somewhere it should be documented what the fee category for an ASIN is, as there are many use cases that could benefit from this.

For example, are the categories here: https://sellercentral.amazon.com/gp/help/external/G200332540?language=en_US, different from https://sellercentral.amazon.com/gp/help/external/GTG4BAWSY39Z98Z3, and are these just the WebsiteDisplayGroups?

**Comment by steven-so** [comment]
We have a need to determine the product category/fee category in order to calculate the referral fee. 

Some things that would be helpful that we haven't figured out how to to if it's already available:

- get fee category of an asin/sku
- get estimated referral fee at a specific price for a given sku/asin 
- documentation on which browse nodes map to which fee categories 
- get referral fee structure for a sku/asin as described here: #334 (https://github.com/amzn/selling-partner-api-models/discussions/334)

**Comment by asilliahmet** [comment]
bumping for activity
