### ISSUE TITLE
Orders API Expose Delivery Instructions to SP-API

### ISSUE THREAD

**Issue by lw-andrewsmith** [amzn/selling-partner-api-models#292]
In the 30 day Order reports a column called Delivery-Instructions is available. This information can contain critical information to ensure an order is fulfilled correctly.

However, it doesn't appear to be available in the Orders API.

Can it please be added @rugved1991

**Comment by tkmik** [comment]
@lw-andrewsmith the same issue, according to documentation GetOrderAddress endpoint contains field 'Delivery Preferences' https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#orderaddress , but when I try to get data, no any information about it and I know that delivery instructions exists, because I created report with type GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING and saw this information
