### ISSUE TITLE
Address 1 information not available in Get orders calls

### ISSUE THREAD

**Issue by Muthukrish28** [amzn/selling-partner-api-models#314]
In the below block we need address 1 details and we are unable to get it. Please help to get this information in get orders call.

 "ShippingAddress": {
                    "StateOrRegion": "TN",
                    "PostalCode": "37064-4738",
                    "City": "FRANKLIN",
                    "CountryCode": "US"
                }

**Comment by rodrifed** [comment]
Hi @Muthukrish28,

**Address** is Personally Identifiable Information (PII), which can only be accessed using a Restricted Data Token.
In order to retrieve this data, you will need to:
1. Apply to a restricted role, if you haven't already applied to one ([Direct to Consumer Shipping](https://developer-docs.amazon.com/sp-api/docs/direct-to-consumer-shipping-restricted-role), [Tax Invoicing](https://developer-docs.amazon.com/sp-api/docs/tax-invoicing-restricted-role) or [Tax Remittance](https://developer-docs.amazon.com/sp-api/docs/tax-remittance-restricted-role))
2. Add the role to your app
3. Get a new refresh token for the selling partner
4. Generate an RDT for the Orders API (more info in [this link](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#tutorial-get-authorization-to-access-pii-for-bulk-orders))
5. Call the Orders API using the RDT from the previous step

Thank you,
Federico
Selling Partner Developer Services

**Comment by Muthukrish28** [comment]
Hi Federico,
Yes. We have created a dev id with necessary roles . But it's not getting approved at all. Is it something your team can help? My I AM user is arn:aws:iam::904089174636:user/Muthukrishnan_Tyr .

This approval is super urgent for our go live implementation. Can you please help

**Comment by rodrifed** [comment]
Hi @Muthukrish28,

Unfortunately, we can't provide support on getting roles approved for your developer profile.
I would suggest that you go carefully through the answer provided by the vetting team, address the areas that were highlighted as non-compliant, and re-submit your role request.

Thank you,
Federico
Selling Partner Developer Services

**Comment by Muthukrish28** [comment]
Thanks a lot for your response. May i know how to reach out to vetting team of Amazon?

**Comment by rodrifed** [comment]
Hi @Muthukrish28,

You have to follow up on the support case that was created when you applied to the new roles.

Thank you,
Federico
Selling Partner Developer Services
