### ISSUE TITLE
FulfillmentLatency / handling_time

### ISSUE THREAD

**Issue by ItHamza** [amzn/selling-partner-api-models#317]
My default handling time is Same-day (0 day), but api doesn't allow to update anything else than positive  integer.
And it doesn't allow to revert handling time of listing to default handling time once it was changed.
I am using 'POST_INVENTORY_AVAILABILITY_DATA' to update handling_time/FulfillmentLatency

**Comment by rodrifed** [comment]
Hi @ItHamza,

The POST_INVENTORY_AVAILABILITY_DATA feed doesn't support setting 0 (zero) day handling time.

However, you can achieve that by using the Listings Items API and the corresponding JSON schemas provided by the Product Type Definitions API.
In order to do it, you should:
1. Obtain a product schema using the [/getDefinitionsProductType operation](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#getdefinitionsproducttype), setting `productType = PRODUCT` and `requirements = LISTING_OFFER_ONLY`
2. Prepare a listings submission that adheres to the JSON schema. Fill the `lead_time_to_ship_max_days` attribute with the handling time (accepted values: from 0 to 30).
3. Submit the listings item using the [/putListingsItem operation](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#putlistingsitem).
4. Validate that the submission was accepted and correctly processed.

For more information, please check the [Building Listings Management Workflows Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide).

Thank you,
Federico
Selling Partner Developer Services
