### ISSUE TITLE
Product Type Definition API -> Add department information for ProductType response

### ISSUE THREAD

**Issue by marketplacehub-com** [amzn/selling-partner-api-models#345]
When retrieving list of product types using [searchDefinitionsProductTypes](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#get-definitions2020-09-01producttypes) operation - it would be create to have department code and department name  information on top of existing product type details inside [ProductType](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#producttype) response.

**Comment by shreeharsh-a** [comment]
Hi,
Thank you for your suggestions. Please provide examples, use cases, etc on how you are planning to use these new fields so that we can fully understand your needs & thus capture them for future consideration.

Thanks!

**Comment by chapmanjw** [comment]
@marketplacehub-com I'm not quite sure I understand the request. Are you looking for the hierarchy of product types, how product types correspond to categories (like the browse tree), or something else?

**Comment by marketplacehub-com** [comment]
> @marketplacehub-com I'm not quite sure I understand the request. Are you looking for the hierarchy of product types, how product types correspond to categories (like the browse tree), or something else?

Yeah, in ideal world - yes. Currently we have plain list of product types which are disconnected from departments and BTG.
We managed generate GET_XML_BROWSE_TREE_DATA report in order to get BTG information with reference of product types. But we are not sure if that is right way of referencing Product Types to BTG. Since it`s XML and it might to be deprecated at some moment. 

Thats why we need some extra info inside ProductType [response](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#producttype) object. Or maybe there should be separate API endpoint which will help to connect Product Types with BTGs or Department at least.

**Comment by chapmanjw** [comment]
@marketplacehub-com Thanks for the clarification. Browse classifications and product types are describing two different concepts. Browse classifications (BTG, etc.) describe the department tree on the retail websites and where items might display in that taxonomy. Product type definitions, on the other hand, describe the attributes needed to describe a specific type of item. There is a relationship between them, but they serve different purposes.

We are planning to build out an API replacement for the browse tree reports on our roadmap (a "Classifications API"). However, since that data is currently available from the GET_XML_BROWSE_TREE_DATA report, we had first prioritized getting new capabilities delivered first (Listings Items API, Product Type Definitions API, etc.). Stay tuned for future announcements on this next year.

In the meantime, however, there may be some smaller incremental changes we could make to aid here, particularly knowing which browse classifications (item_type_keyword, recommended_browse_nodes) are applicable when you already know which product type to use. Would you find it useful if we added the applicable ITK/RBN values as enumeration values on those attributes in the JSON Schemas returned by the Product Type Definitions API?

**Comment by marketplacehub-com** [comment]
Hi @chapmanjw, that should be amazing. As many clarification info(attributes) we can have in Product Type response - that would be easier for us to build better user experience for our clients.

Thanks for sharing roadmap plans. I will keep monitor for new SP API releases for "Classifications API"
