### ISSUE TITLE
[BUG] [SP-API] [Issue] Fulfillment Inbound API v0 - getTransportDetails doesn't return mandatory field value AmazonReferenceId

### ISSUE THREAD

**Issue by dmelendez35** [amzn/selling-partner-api-models#3921]
https://github.com/amzn/selling-partner-api-models/issues/2506

This issue was closed but i  did'n see a fix for it and is happening to me

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
