### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 createInboundPlan  why?  "cannot be more than 1 packline"

### ISSUE THREAD

**Issue by shadowJourney** [amzn/selling-partner-api-models#3922]
![2](https://github.com/amzn/selling-partner-api-models/assets/112471375/bc2c6b8e-4d91-407c-9a7f-6870d1f0ffad)
![5](https://github.com/amzn/selling-partner-api-models/assets/112471375/f5b9a5ac-7be3-4855-9a80-3ffc8d719d7e)
why?
"There cannot be more than 1 packline of individual unit of the same merchant SKUs while saving sku boxes"

There's no hint of what we're going to do, what we're going to do next, what we're going to do and how we're going to adjust.?

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
