### ISSUE TITLE
API feed : apparel_size.size issue

### ISSUE THREAD

**Issue by alexglvr** [amzn/selling-partner-api-models#3969]
Hello,

I try to feed my Amazon Seller account From magento using M2E Pro module.

Despite the help of both support Teams, the issue is still unsolved.

I have this error : 

"Sur la base des données de « [apparel_size#?.size_class, apparel_size#?.size_system, age_range_description.value, target_gender.value] », la valeur « 12 ans » du champ « "size" » pour l'attribut « apparel_size » est invalide. Merci de fournir une valeur valide."

I am an Amazon FR, Product type is Sweatshirt (node 464886031 / 464949031), Age Range : Enfant (Kid), Gender :  Unisexe, Size_system: FR / ES, Size_class: Âge and the Size : 12 ans

I have the same error for all the product variation when using size type "x ans"

Theorically, this size type is allowed for this product type / Age Range / Size System / Size_Class...

Thank you for your help,

**Comment by harguph** [comment]
Hello @alexglvr ,

Thank you for bringing this up.

Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
