### ISSUE TITLE
Selling Partner API (SP API) : ApiError : Fulfillment Inbound : POST generate Transportation Options issue

### ISSUE THREAD

**Issue by qdev89** [amzn/selling-partner-api-models#3972]
hi all,
I try to use https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generatetransportationoptions 

with body:
`{
    "placementOptionId": "pl1b776844-7cfb-4d6c-b823-fe4ab80a6b03",
    "shipmentTransportationConfigurations": [
        {
            "freightInformation": {
                "declaredValue": {
                    "amount": 5.5,
                    "code": "CAD"
                },
                "freightClass": "FC_50"
            },
            "pallets": [
                {
                    "dimensions": {
                        "height": 5,
                        "length": 3,
                        "unitOfMeasurement": "CM",
                        "width": 4
                    },
                    "quantity": 2,
                    "stackability": "STACKABLE",
                    "weight": {
                        "unit": "KG",
                        "value": 5.5
                    }
                }
            ],
            "readyToShipWindow": {
                "start": "2024-06-22T00:00:00.000Z"
            },
            "shipmentId": "shf851d792-a9ad-4c93-aa22-86caf8b10274"
        }
    ]
}`

it returned an operationId and when I checked with /inbound/fba/2024-03-20/operations/:operationId I get the issue

`{
    "operationStatus": "FAILED",
    "operationId": "d871dda8-999e-4736-8762-b7acd635f92c",
    "operation": "generateTransportationOptions",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "BadRequest",
            "message": "ERROR: Fail to execute COMPUTE_TRANSPORTATION_OPTIONS API with errors."
        }
    ]
}`

I'm totally stuck on this step you can check

thanks

**Comment by harguph** [comment]
Hello @qdev89 ,

Thank you for bringing this up. 

It seems to be an issue with the input request i.e. the body of "generateTransportationOptions" which you are sending to the API.

Per the document [here](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#request-body-11) the api request requires "contactInformation" which seems to be missing in your request. Please check and confirm the request is complete and is not missing any required information and try again.

In-case if this does not solve the issue, please feel free to reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

Regards
