### ISSUE TITLE
Error: Operation ListInboundPlanItems not supported for Send-to-Amazon inbound plans in Fulfillment Inbound API V0

### ISSUE THREAD

**Issue by Tyapkin** [amzn/selling-partner-api-models#3977]
#### Problem:
When attempting to perform the operation ListInboundPlanItems on Fulfillment Inbound API V0 shipments that have been converted to Send-to-Amazon inbound plans, a BadRequest error is returned.

#### Error Details:
- **Code:** BadRequest
- **Message:** ERROR: Operation ListInboundPlanItems is not supported for Fulfillment Inbound API V0 shipments that have been converted to Send-to-Amazon inbound plans.
- **Details:** N/A

**Comment by shreeharsh-a** [comment]
@MeenaAmz

**Comment by rugved1991** [comment]
Hi @Tyapkin,

This is expected behavior. The Fulfillment Inbound v0 API does not provide interoperability between the API and the Send to Amazon flow on the UI. 
We recommend that you migrate over to the newly launched version of [Fulfillment Inbound API v2024-03-20](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference). Plans created with the Fulfillment Inbound API can be accessed and edited on Amazon's UI (called [Send to Amazon](https://sellercentral.amazon.com/help/hub/reference/G6925SDD66GDLXJW)) and vice versa. 

Best,
Rugved
Solutions Architect, SP-API
