### ISSUE TITLE
getCatalogItem is missing data

### ISSUE THREAD

**Issue by chastain1337** [amzn/selling-partner-api-models#3984]
getCatalogItem 2022-04-01
ASIN: B016YUBRBA
Marketplace IDs = ["ATVPDKIKX0DER"]
Included data = summaries, attributes

In the response the "brand" is null, but I can see by visiting the listing (https://www.amazon.com/gp/product/B016YUBRBA) that there is definitely a brand.

**Comment by harguph** [comment]
Hello @chastain1337 ,

Using the getCatalogItem api, I was able to get the "brand" data in attributes for a different ASIN in a different marketplace. 

<img width="1070" alt="Screenshot 2024-06-24 at 17 52 20" src="https://github.com/amzn/selling-partner-api-models/assets/89893499/b168e045-918b-4b13-87bc-2252b9c9cf8e">

It seems to be an issue with the listing of this specific ASIN. Kindly try with a different ASIN to check and confirm the same. 

In-case the issue persists, please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

Regards
