### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 Why is Amazon partnered carrier selected by default?How to use Fulfillment Inbound API v2024-03-20 to modify the carrier to a non-Amazon partner carrier

### ISSUE THREAD

**Issue by Ironkyy** [amzn/selling-partner-api-models#4002]

**Comment by Ironkyy** [comment]
Why is the default AGL selected for shipments created using Fulfillment Inbound API v2024-03-20? How to change it to Non-Amazon-partnered carrier?

**Comment by he0212** [comment]
Excuse me, may I ask a relevant question about how you check your shipment carrier belongs to partnered-carrier or non-partnered?    
All of the carrier information my team get is non-partnered carrier.  We estimate it by  `listTransportationOptions`'s  response key `shippingSolution` , and all of the responses' shippingSolution value are”USE_YOUR_OWN_CARRIER“, which is opposite to the another value "AMAZON_PARTNERED_CARRIER".
I wonder if my way is avalible? Since my situation is the complete opposite of yours····

**Comment by Jeff-wangjunchang** [comment]
In the Fulfillment Inbound API v2024-03-20, the listTransportationOptions response shows that all `shippingSolution` are `USE_YOUR_OWN_CARRIER`. However, when creating an inbound shipment in Amazon Seller Central, it can select `UPS(Amazon partnered carrier)`

**Comment by he0212** [comment]
> In the Fulfillment Inbound API v2024-03-20, the `listTransportationOptions` response shows that all `shippingSolution` are `USE_YOUR_OWN_CARRIER`. However, when creating an inbound shipment in Amazon Seller Central, it can select `UPS(Amazon partnered carrier)`

You are right. Inboud API v2024-03-20 doesn't provide any PCP relevant options for us to choose, at least for now.

**Comment by utexasscott** [comment]
Like the other commenters, we also are getting no Amazon Partnered Carrier responses.

We are only getting 15 options like this:
shippingMode: FREIGHT_LTL
shippingSolution: USE_YOUR_OWN_CARRIER

**Comment by Ironkyy** [comment]
Guys, has anyone obtained Air small parcel or Air small parcel express shipping method?
