### ISSUE TITLE
[BUG][SP-API]The FBA inventory report for the Mexican marketplaces returned an error

### ISSUE THREAD

**Issue by Ming20240706** [amzn/selling-partner-api-models#4009]
Why is it normal for the United States, Canada, and even Brazil to request FBA inventory reports, while Mexico has been prompting InvalidInput.

"message": "Report rejected for this client. Some of the marketplaces are not allowed for this Report",

**Comment by jawheral** [comment]
Hi @Ming20240706,

Some reports, including FBA inventory reports, are only available to specific Marketplaces. You are receiving this message because you are most likely creating a report that is not available for the Mexico marketplace.

Can you please provide more information on which report exactly are you referring to?

Additionally, please refer to this [FBA reports docs page](https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba) for more information on specific reports and their availabilities.

Best,
Jawher
Selling Partner API Solutions Architect
