### ISSUE TITLE
REPORTS API is inconsistent:  GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA report mostly fails

### ISSUE THREAD

**Issue by pradeep-gox** [amzn/selling-partner-api-models#4032]
I am trying to download fba inventory report. I am only able to create that only 1 out of 20 requests. The getReport response payload shows that the processingStatus as FATAL without any information regarding what's the issue.

Here is the request ID:

x-amzn-RequestId -  b2ad106d-565d-418b-a139-2e695c344388

**Comment by rugved1991** [comment]
Hi @pradeep-gox,

The FBA Manage Inventory report is updated in near-real time. A near-real time FBA report is generated no more than once every 30 minutes. This means that after a near-real time FBA report is generated following your report request, a 30-minute waiting period must pass before Amazon will generate an updated version of that report.
If you call the report in between these 30 minutes, you will receive a FATAL report as the new report cannot be generated due to the limitation. 
Please check the frequency by which you are calling these reports and make sure you are adding 30 minutes delay between two calls.
If you are still seeing the same issue by making calls 30 minutes apart, then please confirm if some other developer has generated the same report for the seller you are working within those 30 minutes. You can call the getReports API call to check if there already exists a report  that was generated within the 30 mins time window.

Best,
Rugved
Solutions Architect, SP-API

**Comment by kmizzi** [comment]
@rugved1991 I'm experiencing the same.  I'm only calling uniquely once per hour but each hour I call 4x for North America for example, each request having the marketplaceId being unique (US, CA, MX, BR)

Could this be causing an issue?  Passing different marketplaceIds produces different results so we need to do it this way.
