### ISSUE TITLE
The order number queried by getFulfillmentOrder is inconsistent with the FULFILLMENT_ORDER_STATUS notification

### ISSUE THREAD

**Issue by qq344275409** [amzn/selling-partner-api-models#4036]
![001](https://github.com/user-attachments/assets/3e420b58-d709-4042-8523-0ccdd365ebcb)
![002](https://github.com/user-attachments/assets/83506e18-757d-4fdd-a079-e3b256059125)
Is this normal?

**Comment by rugved1991** [comment]
Hi @qq344275409,

Thanks for surfacing this issue. It looks like this issue would need some additional troubleshooting to figure out the root cause. Can you please open a [developer support case](https://developer.amazonservices.com/support) and provide the complete request response details along with headers? This would help the developer support team to investigate the issue further.

Best,
Rugved
Solutions Architect, SP-API
