### ISSUE TITLE
[API Feature] API to update offer start date

### ISSUE THREAD

**Issue by etsourcing2** [amzn/selling-partner-api-models#404]
Does anyone know where is the API endpoint to update the listing "Offer start date"? I cannot find from the pricing feed nor any other feed.
https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md
![image](https://user-images.githubusercontent.com/79884940/133586853-2a16fe53-5c8a-4ae6-89da-e732c672e62a.png)

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
