### ISSUE TITLE
Document the new requirement to start FBA-inbound-shipment IDs at "1"

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#405]
Amazon recently sent out an email alert linking to https://docs.developer.amazonservices.com/en_US/fba_guide/FBAGuide_ShipLabelSpec.html which indicates a requirement to start FBA-inbound-shipment IDs at "1".  This is a very good thing, and can greatly simplify the process.  (See my original request for this change here: https://github.com/amzn/selling-partner-api-models/issues/371 although that earlier bug still needs work.)

This should be documented on https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getlabels

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
