### ISSUE TITLE
Is it possible to see the amount of `afn-future-supply-buyable` for a given inbound Shipment?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#407]
Is it possible to see the amount of `afn-future-supply-buyable` for a given inbound Shipment?  I'm trying to predict whether a sell-out situation will occur, but if multiple shipments are inbound, it's unclear where the `afn-future-supply-buyable` is currently coming from.

Are there no Reports involving Shipments at all?  (See also bug amzn/selling-partner-api-models#378 there.)

See also bug amzn/selling-partner-api-models#375.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
