### ISSUE TITLE
Approval for Amazon SP-API Developer Profile updated with Restricted Access Request

### ISSUE THREAD

**Issue by RamaIT** [amzn/selling-partner-api-models#4075]
Tried requesting several time to get Restricted Access Request approved in Developer profile but it keeps getting rejected that we don't meet certain Data governance, Encryption, Retention etc criteria, without explaining what is required. 

Can someone please assist with getting the Amazon profile updated?

**Comment by jawheral** [comment]
Hi @RamaIT,

Did you go through the [Policies and Agreements](https://developer-docs.amazon.com/sp-api/docs/policies-and-agreements) needed for SP-API developers?

Additionally, you can check the Security and Compliance section of the developer docs, e.g [Logging and Monitoring for Amazon API Applications](https://developer-docs.amazon.com/sp-api/docs/protecting-amazon-api-applications-data-encryption) or [Key Security Control Guidance](https://developer-docs.amazon.com/sp-api/docs/guidance-to-address-key-security-controls-in-sp-api-integration).

Still, if you aren't able to pinpoint the issue, kindly contact [Developer Support](https://developer.amazonservices.com/support). The [support guidelines](https://developer.amazonservices.com/support-guidelines) should be followed for optimal case creation.

Due to our inability to provide further support on developer access on Github, I'm closing this issue.

Best,
Jawher
Selling Partner API Solutions Architect
