### ISSUE TITLE
does "Unsellable" detail exist somewhere, in some report?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#408]
The `GET_FBA_MYI_ALL_INVENTORY_DATA` report has `afn-unsellable-quantity` and `afn-reserved-quantity` columns for showing issues that make the inventory not available for sale.

Then the `GET_RESERVED_INVENTORY_DATA` exists to show detail on `afn-reserved-quantity` to see which type of the reserved it actually is.

However, there is no `GET_UNSELLABLE_INVENTORY_DATA` report as one would expect, given the existence of `GET_RESERVED_INVENTORY_DATA`.

Is there some report containing this missing "Unsellable" detail?  Some examples of the possible values "Unsellable" can take are "Expired" and "Warehouse Damaged", as per the Seller Central web console.

(See also bug amzn/selling-partner-api-models#378.)

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
