### ISSUE TITLE
Where in the API is "Ships In Own Container" status for ASINs or SKUs?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#409]
I suspect this is set at the ASIN level, but even that is unclear. The only way I know of to assess whether an ASIN has this flag is to go to the product detail page and look for "Shows what’s inside. To hide it, choose Ship in Amazon Packaging at Checkout." a little below the "Add to Cart" button.

Where is this in the API? A report or REST query?

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
