### ISSUE TITLE
Feed size limit

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4097]
Hello, I got "feed messages list beyond allowed size", the docs say "Keep file size less than 10 MiB (5*221, or 10,485,760 bytes). If your file exceeds the recommended size, please adjust by dividing it in different smaller submissions." ... but "recommendation" should be just a recommendation, so the hard limit is how much? Or the 10MB is a hard limit but docs call it "recommendation"?

Thank you

**Comment by NoxArt** [comment]
Also I heard there is yet another undocumented(?) limit of 10k messages ... all these limits are ok for tiny sellers but crippling for anyone below medium and larger, if I need to make a bulk change across marketplaces I will need to send 300 feed files? And that's while still being a relatively small seller. On XML feed it worked fine

**Comment by jawheral** [comment]
Hi @NoxArt,

It seems that you are referring to the [JSON_LISTINGS_FEED](https://developer-docs.amazon.com/sp-api/docs/listings-feed-type-values#listings-feed). This feed is recommended from 1500 listings but has a limit of 10000 messages which is probably why you are receiving the error "feed messages list beyond allowed size".

This limit is mentioned in the table below this [section](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#should-i-submit-in-bulk-using-the-json_listings_feed-or-individually-with-the-listings-items-api).

I would suggest that you go through your use case and answer questions such as:
- Are these bulk changes actually needed immediately for all listings?
- Can't these changes be split and rolled-out over time?
- Are they all needed or is there some sort of duplication?
- Can the listings maintenance process be changed so that listings are handled using the Listings API as well? such as using the patchListingsItems to update certain items.
- What's triggering this bulk change? can listening to notifications for certain listings and acting on it serve the use case?

I'm also open to learn more about your use case.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by NoxArt** [comment]
1) Yes, Amazon is requiring us to update all listings stating they will ban our marketplace if we don't comply
2) We are trying, but it's technically challenging
3) Yes, all is needed
4) No way ... how would API help if there are too many items even for a bulk change? We can't make 50000-100000 API requests
5) No trigger, business requirements usually ... and usually with a strict deadline/threat "your account is at risk" etc.

XML had way larger limits and apparently it was possible. The neverending influx of new Amazon's business or technical requirements is overwhelming our dev department (and mental state)

Thank you

**Comment by jawheral** [comment]
Hi @NoxArt,

Thanks for the additional details. Can you also specify what kind of business requirements for example and how these affect all of your listings at once thus triggering the need to update all your listings?

**Comment by NoxArt** [comment]
I'm sorry for delay

They are usually requirements to add a various sort of Compliance information to a certain type of product where we have only a few types of products, so when type = batteries it's like 80% of our listings.
From the recent times: Add "are batteries required, add Compliance media safety document, add Safety information images, add is expiration dated product..."

There is more fun to be had, just this morning Amazon inexplicably revived tens of thousands of our **deleted** listings and put them to Health Center because they are missing Compliance information ... of course we didn't update them when they are listed as "OperationType = Delete" in our feed. And now we have to figure out what to do and potentially update our whole portfolio as well

**Comment by NoxArt** [comment]
Right now I already implemented splitting feeds into parts and working on implementing an upload queue to accomodate for throttling limits

**Comment by jawheral** [comment]
@NoxArt 
Thank you for providing the valuable feedback. 
We are happy to learn more once you have further feedback after the implementation.

Regarding the deleted listings issue, I recommend that you contact [Seller Support](https://sellercentral.amazon.com/help/hub/support) and communicate the issue so our teams can see whether this is expected or a bug.

Best,
Jawher
Selling Partner API Solutions Architect
