### ISSUE TITLE
SP-API Developer: update profile with Direct to Consumer Delivery

### ISSUE THREAD

**Issue by juliocabrerizo** [amzn/selling-partner-api-models#4105]
Hello,

Amazon keeps rejecting our request of Developer Profile Update. 
We were able to obtain a public developer profile for our customer, but now we need to update the profile to be able to access restricted data by checking the “Direct to Consumer Delivery” box.
Over the past few months we have requested this and received the same message. We want to include this role in our profile, as we need the customer data to manage the shipping of FBM orders.

case 10003156682

**Comment by jawheral** [comment]
Hi @juliocabrerizo,

Please work with Developer Support on your case to find out about the requirements needed for your website or other requirements so that you can get the access.

We are unable to provide API access support on the Github repository.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by juliocabrerizo** [comment]
thanks @jawheral , could you please then tell me where I can get in touch with Developer support or email?

**Comment by jawheral** [comment]
Hi @jawheral,

You can reach developer support [here](https://developer.amazonservices.com/support).

Best,
Jawher
Selling Partner API Solutions Architect
