### ISSUE TITLE
[BUG] Financial Events AdjustmentEventList values missing order id.

### ISSUE THREAD

**Issue by michael-land** [amzn/selling-partner-api-models#412]
![image](https://user-images.githubusercontent.com/33362998/143950620-fa274bd6-5095-4115-96c1-2e42ba0e6fce.png)

it's impossible to identify the owner of these adjustments without order id when calling GET /finances/v0/financialEvents

The workaround is to use listFinancialEventsByOrderId, but it's too slow due to rate limit in our case.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
