### ISSUE TITLE
[BUG] Missing BuyerTaxInfo  | Order -> BuyerInfo -> BuyerTaxInfo is null

### ISSUE THREAD

**Issue by kevinvenclovas** [amzn/selling-partner-api-models#414]
Hi,

the api work very well but i have one question every time i requested an order the "BuyerTaxInfo" is null. With the old MWS-Api i get all this informations.

I already use  the RestrictedResource to request the "buyerInfo", "shippingAddress" but this information always remain null.

So how can i get the "BuyerTaxInfo"? Is there n extra function to request thsi information?

Maybe ther is a simple solution. Someone have an idea?

**Comment by soluga** [comment]
I worked with feeds and reports the last couple of years. It worked but was a hassle lot of time.
Since most of the Feed-Uploads are now deprecated (and will not be available after 03/2025) I thought it would be a good time to completly switch from feeds and reports to native SP-API-calls.

But without the billing-address this won't work. I think amazon will also deprecate most of the reports sooner or later, so we have to switch over to SP-API, but currently there is just no way of doing this. The billing address (not only the tax-information!) is an essential information.

It doesn't seem that amazon knows about this or is willing to change anything right now.

**Comment by benjiam-gh** [comment]
I'm still having the same problem. Has someone found a solution to retrieve VAT numbers for AFN orders without having Amazon VAT Calculation Service active?

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by tom-it** [comment]
did anyone manage to get tax id through SP api?
