### ISSUE TITLE
How to test listing items creation and notifications API production-like using sandbox?

### ISSUE THREAD

**Issue by brunoamorimdev** [amzn/selling-partner-api-models#4142]
Hi,

I’m wondering if there’s a way to test the [getListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#getlistingsitem) and [putListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#putlistingsitem) endpoints using the sandbox environment, similar to how they would function in production.

I would like to create at least two products and test other endpoints, such as the Reports API and Notifications, where I can change product attributes to trigger notification events and request item reports.

If testing in the sandbox is not possible, is there a safe way to test in production? For example, by creating a sample product with the lowest possible price, or using other precautions?

Any help or pointers to the appropriate documentation would be greatly appreciated.

Thank you for your assistance!

Best regards,
Bruno

**Comment by mafge** [comment]
Hi @brunoamorimdev,
thanks for reaching out!
In order to test you can use the [Selling Partner API sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox#selling-partner-api-sandbox-endpoints). Please note that Listings API only supports the static sandbox which has its limits (you always get the same response independent of the request data). For Listings API you can also use [Validation Preview mode](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#mode) which will execute the synchronous validations of each endpoint without persisting any data in the backend. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by brunoamorimdev** [comment]
Hi @mafge 

Thanks for the answer.

Actually I need to "test in production", which means be able to create a sample product in production and perform changes in it to check out the notifications that are triggered when these changes are performed and all that stuff that only production env offers. 
If that's a possibility I would like to know what are the recommendations to create this sample product in production and how these tests should be performed. I see this as a possibility because while searching for these products in the amazon marketplace, I found examples that probably were used as testing samples by other sellers integrating to the SP API.

Thank you for your assistance!

Best regards,
Bruno

**Comment by mafge** [comment]
Hi @brunoamorimdev,
we do not have any documentation for "test in production". However you can just go ahead and create listings for products (choose products that are not very popular and unlikely that someone buys it) and try to avoid that your listing gets the buy box offer. Hope that helps!

**Comment by brunoamorimdev** [comment]
Hi @mafge,

Thank you for the quick response! Your guidance is very helpful. I’ll proceed with creating listings for less popular products and will make sure to avoid getting the buy box offer. If I run into any issues or have further questions, I’ll reach out.

Thanks again!

Best regards,
Bruno
