### ISSUE TITLE
No documentation/API on "Subscribe & Save"

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#415]
There is a https://sellercentral.amazon.com/fba/programs/sns/manage page which allows for manual SnS management. But seemingly all of that is missing from the API.  Among the things missing from the API:

* List `ASIN`/`SKU` products in SnS, showing `Total subscriptions` and `Seller-funded discount`
* Add products to SnS
* Remove products from SnS
* Change the `SKU` that an SnS `ASIN` points to
* Change the `Seller-funded discount`

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
