### ISSUE TITLE
Missing documentation on CreateFeedSpecification.feedOptions

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#416]
According to the `CreateFeedSpecification` documentation at https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feeds_2021-06-30.md#feedoptions there are:
`Additional options to control the feed. These vary by feed type.`

But what are the options?

As least one option seems to exist, at least internally, which is that the `POST_FLAT_FILE_LISTINGS_DATA` feed can return either a CSV file or an Excel file.  But this is not documented.  Seller Support actually claims it's not in the SP-API at all.  Either way, it should be documented whether these options exist, or don't currently exist but may be added in the future.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
This bug should remain open until the underlying issue is fixed. Can this be moved to a discussion or whatever is necessary to keep the bug report open so it's easy to find?
