### ISSUE TITLE
Since this morning, the createInboundPlan interface has the problem "We encountered an internal error. Please try again"

### ISSUE THREAD

**Issue by asd6979448** [amzn/selling-partner-api-models#4183]
Can anyone tell me what's going on?

**Comment by asd6979448** [comment]
这个错误不是每次都会发生。当我将物品分成 5 个或更多箱子时就会发生这种情况。

**Comment by asd6979448** [comment]
This error doesn't happen every time. It happens when I split the items into 5 or more boxes.

**Comment by asd6979448** [comment]
This error doesn't happen every time. It happens when I split the items into multiple boxes.

**Comment by mafge** [comment]
Hi @asd6979448,
sorry for the inconveniences and thanks for reaching out!
Does this happen when you select a placement option with multiple shipments? I am asking because there is a known issue with multiple shipments that is currently investigated by the team.
Thanks,
Marc
Selling Partner Developer Services

**Comment by Ironkyy** [comment]
When do you expect this issue to be resolved?
