### ISSUE TITLE
Amazon Report Access forbidden

### ISSUE THREAD

**Issue by Vladiuse** [amzn/selling-partner-api-models#4202]
Hello. im try to create **GET_FBA_INVENTORY_PLANNING_DATA**
Get response: sp_api.base.exceptions.SellingApiForbiddenException: [{'code': 'Unauthorized', 'message': 'Access to the resource is forbidden', 'details': ''}]

GET_FBA_INVENTORY_PLANNING_DATA Report need **Amazon Fulfillment**

But i can create successfully GET_FBA_MYI_ALL_INVENTORY_DATA with Role: Pricing, Amazon Fulfillment
so i have **Amazon Fulfillment** role. What the trouble?

here my code:
amazon_seller_credentials = {
	'refresh_token': config.amazon_config.SELLER_SP_API_REFRESH_TOKEN,
	'lwa_app_id': config.amazon_config.SELLER_LWA_CLIENT_ID,
	'lwa_client_secret': config.amazon_config.SELLER_LWA_CLIENT_SECRET,
}

sp_api_reports = Reports(credentials=amazon_seller_credentials, marketplace=Marketplaces.DE)
report = sp_api_reports.create_report(
	reportType=ReportType.GET_FBA_INVENTORY_PLANNING_DATA,
)

**Comment by mafge** [comment]
Hi @Vladiuse,
thanks for reaching out!
The provided information looks reasonable for me, let me give you some general hints on Reports API so that you can further debug your issues:
- Please make sure that you have the required roles - you can check this in Seller Central.
- Please make sure that you are registered for the marketplaces you want to request a report - you can check this in Seller Central.
- Please make sure that your credentials are valid and your access token is not timed out.
- The report you want to request is only available for Sellers and not for Vendors.
If all of the above points did not help, please feel free to reach out to our [Developer Support](https://developer.amazonservices.com/support).
Best,
Marc
Selling Partner Developer Services
