### ISSUE TITLE
DSA Responsible person

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4218]
Hello, we need to fill in DSA responsible person address into our products
According to this article https://marco-tibaldeschi.medium.com/handling-gpsr-using-amazon-sp-api-165ddd6cafae there should be dsa_responsible_party_address in SP API ... however if I query schema for either PRODUCT or BATTERY then it is not there ... there are 0 hits for even just "dsa" or "responsible" in the schema json

![image](https://github.com/user-attachments/assets/bce87fc6-37fe-4a2f-88eb-91eb1249d138)

Curiously, while I couldn't find some of the newer attributes required by Amazon in the old feed, this one seems to actually be there

![image](https://github.com/user-attachments/assets/44ea0941-6eb1-428d-8505-4dd1ca64bc93)

(though the structuring makes it pretty hard to determine where it should be placed)

Am I searching wrong, should be it be there (or somewhere else)?

Or if not, when can we expect it to be made available?

**Comment by NoxArt** [comment]
I tried Germany marketplace and it's not there either

**Comment by jawheral** [comment]
Hi @NoxArt,

Thanks for reaching out. It seems that you are searching for the UK marketplace and the `dsa_responsible_party_address` is not available there as it might be that the UK is not affected by the GPSR compliance. The other attributes such as `gpsr_safety_attestation` are global that's why you'd still find them in all marketplaces. The `PRODUCT` product type wouldn't include the attribute as well.
I was able to find the `dsa_responsible_party_address` with the `BATTERY` product type in Germany marketplace. Please take the specific product type for your product and fetch the schema in affected EU marketplaces such as Germany, France, Italy, etc...

Best,
Jawher
Selling Partner Developer Services

**Comment by NoxArt** [comment]
Oh ok, so it's not in PRODUCT but it's in BATTERY AND EU marketplace

Thank you for help

**Comment by jawheral** [comment]
@NoxArt BATTERY is just one product type that includes the attribute. Multiple other product types in EU include it as well (SHIRT, CUP_HOLDER,...). 
The GPSR compliance affects non-food products so all of the related non-food product types in EU might include the attribute.

Happy to help

Best,
Jawher
Selling Partner Developer Services

**Comment by NoxArt** [comment]
Thank you very much, we may not have much luck elsewhere but here on github we always get a quick and helpful replies!

**Comment by NoxArt** [comment]
I have submitted a feed with these values and they were visible in the administration but a few hours later they were empty again, is it possible that the values get overwritten / cleared somehow? We still also run legacy XML feeds - maybe they did it? We should be making a switch to JSON-only soon but want to be careful so it's slow

**Comment by jawheral** [comment]
Hi @NoxArt,
Please make sure the listing values are not being overwritten by other operations on the same listing such as legacy XML feeds. You can always check the listing attributes with the getListingsItem operation by adding `attributes` as part of the `includedData` parameter.

Best,
Jawher
Selling Partner Developer Services
