### ISSUE TITLE
The following MSKUs are not available for inbound

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-models#4257]
Dear All,

Is there a way to know if an SKU is ready for the Inbound process?
I have just listed an SKU and then waited for the Feed status=DONE, but calling the setPrepDetails then got the below error

_"The following MSKUs are not available for inbound. If these were recently added, please try again later"_

Call the API getListingsItem, return Status=DISCOVERABLE

@mafge 

Thank you

**Comment by mafge** [comment]
Hi @hamduc7,
thanks for reaching out!
In order to use a SKU for fulfillment inbound, it needs to have an `ASIN` as well as a `FNSKU` assigned to it. You can check whether these values are set by using getListingsItem from Listings Items API. Hope that helps!
Best,
Marc
Selling Partner Developer Services
