### ISSUE TITLE
Fulfillment Inbound API v2024-03-20  Is the delivery date all today?

### ISSUE THREAD

**Issue by tian880** [amzn/selling-partner-api-models#4259]
![~KBM{9W7`0B M88L3H(O8Q5](https://github.com/user-attachments/assets/4a8a34b5-7a2a-4b1a-b43a-07646f85f6a8)
I found that all the shipping dates created by previous APIs are today

**Comment by tian880** [comment]
The API created by the received shipment has also become what it is today

**Comment by weilinggu** [comment]
@tian880 Can you clarify what was the issue and how did you get this issue?
Which API endpoint did you use?

Weiling
Amazon Selling Partner Services

**Comment by tian880** [comment]
endpoint:ATVPDKIKX0DER generateTransportationOptions setReadyToShipWindow Amazon backend is always the latest time (today)

**Comment by tian880** [comment]
Another issue is that generateDeliveryWindowOptions only returns a 7-day international shipment interval, while the document shows a 14 day interval
![image](https://github.com/user-attachments/assets/8ded3772-a46a-430b-9c96-dc349e4b9321)

**Comment by ccyun06** [comment]
#4102 @weilinggu Please take a look at this issue, it’s similar.

**Comment by puppsupr** [comment]
Hi @tian880,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end. Please open the case with full request and responses along with the inboundPlanId.
