### ISSUE TITLE
/SetPackingInformation    [{"code":"InternalServerError","message":"ERROR: A server-side error occurred processing the operation SetPackingInformation.","severity":"ERROR"}]

### ISSUE THREAD

**Issue by Ironkyy** [amzn/selling-partner-api-models#4261]
This problem occurred when I went to setPackageInfo. It has never happened to me before. Does anyone know what the problem is?

**Comment by Ironkyy** [comment]
Caught an IRE calling the herd client to openAndProcessWorkItem for workflow wfef90f956-ade3-4a6b-a82d-b6fbd6cd6f59 for seller XXXXXXX    what that mean?

**Comment by puppsupr** [comment]
Hi [Ironkyy](https://github.com/Ironkyy),
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

**Comment by johnkw** [comment]
Saw that for first time recently. Since it's right at the beginning of everything I just deleted the workflow and restarted.

**Comment by BluePositive** [comment]
@puppsupr why is this closed????
