### ISSUE TITLE
A server-side error occurred processing the operation UpdateShipmentTrackingDetails

### ISSUE THREAD

**Issue by albertqiu2024** [amzn/selling-partner-api-models#4296]
when i try to update shipemnt tracking detail i got the error `A server-side error occurred processing the operation UpdateShipmentTrackingDetails`

api: `/inbound/fba/2024-03-20/inboundPlans/wf49107c58-865e-4b3d-b9f9-2b2ff8fec0b0/shipments/sh404ab3c9-c362-4e2f-80bb-8917d943fca2/trackingDetails` 
body: ``
{
        "trackingDetails": {
            "ltlTrackingDetail": {
                "freightBillNumber": [
                    "15505749597619"
                ]
            }
        }
``
operationId: `b2d6ddb5-8d00-475b-95bb-d06e54cc8d58`  
response: `ERROR: A server-side error occurred processing the operation UpdateShipmentTrackingDetails.`

**Comment by puppsupr** [comment]
Hello,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.
Thanks,
Selling Partner API Developer Services
