### ISSUE TITLE
GenerateTransportationOptions issue on checking InboundOperationStatus

### ISSUE THREAD

**Issue by membra99** [amzn/selling-partner-api-models#4298]
I have a problem when calling the "GenerateTransportationOptions" api endpoint. In the response from this call, I get the status 200 and the corresponding "OperationId". During the next call and status check "GetInboundOperationStatus" I get an error as in the picture below. Does anyone know what this is about ?

![image](https://github.com/user-attachments/assets/c3b79313-bcb5-494f-b9ad-0c720102cafd)
![image](https://github.com/user-attachments/assets/2597fd8b-6ba8-48f6-8c3f-167c3f565cee)

**Comment by zaki-siddiqui** [comment]
We're experiencing the same issue. It would be greatly appreciated if someone could suggest a fix.

**Comment by puppsupr** [comment]
Hi,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.
Thanks,
Selling Partner API Developer Services
