### ISSUE TITLE
[BUG] [SP-API] [Issue] GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL frequently raises Quota limit error

### ISSUE THREAD

**Issue by wolendranh** [amzn/selling-partner-api-models#430]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL

## Expected Behavior

Report can be requested with same quota limits as other reports.

## Current Behavior

Currently it is possible to request 3-4 reports per hours. After that quota limit is raised.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
