### ISSUE TITLE
Address Update Not Reflected in getShipments v0 After updateSourceAddress v2024-03-20.

### ISSUE THREAD

**Issue by hourloop-deanlin** [amzn/selling-partner-api-models#4304]
After using `updateShipmentSourceAddress` from v2024-03-20 to update the address, we confirmed the success by checking the status with `getInboundOperationStatus`.

However, when using `getShipments` from v0 to check the same shipment, the `shipToAddress` remains unchanged. Only `getShipment` from v2024-03-20 returns the updated address.

Since the v0 `getShipments` is not scheduled for deprecation, this behavior appears to be a bug.

**Comment by mafge** [comment]
Hi @hourloop-deanlin,
thanks for reaching out!
Please note that `ShipmentSourceAddress` is not the address your items will be shipped to, but shipped from. This means that `updateShipmentSourceAddress` has no effect on the shipping address.
Best,
Marc
Selling Partner Developer Services

**Comment by hourloop-deanlin** [comment]
Hi @mafge, I made a typo earlier. It should be `shipFromAddress`, not `shipToAddress`.

**Comment by mafge** [comment]
@hourloop-deanlin No worries. Yes, this way it makes sense. Given the fact that v0 is deprecated and most of the operations are gone by end of this year, chances of this bug getting fixed are fairly low to be honest. I encourage you to look into migrating to the newest version in the future, because improvements will only be made on the new API. However, in the meantime you should still be able to use [updateInboundShipment](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#updateinboundshipment) from v0 to update `shipFromAddress`.

**Comment by hourloop-deanlin** [comment]
@mafge Got it, thanks.
