### ISSUE TITLE
POST /vendor/directFulfillment/shipping/2021-12-28/shippingLabels/{purchaseOrderNumber} InternalFailure

### ISSUE THREAD

**Issue by a224327780** [amzn/selling-partner-api-models#4305]
request body
```
{"sellingParty":{"partyId":"xxx"},"shipFromParty":{"partyId":"xxx"},"containers":[{"containerType":"pallet","containerIdentifier":"1","weight":{"unitOfMeasure":"KG","value":"29.2"},"packedItems":[{"itemSequenceNumber":1,"packedQuantity":{"amount":2,"unitOfMeasure":"Each"}}]}]}
```

response
```
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
```

- The request is normal after canceling the containers parameter

**Comment by puppsupr** [comment]
Hi [a224327780](https://github.com/a224327780),
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.
Thanks,
Selling Partner API Developer Services
