### ISSUE TITLE
Finances API v0 - can not get shipment events for orders created after Nov 1st

### ISSUE THREAD

**Issue by dsokolowski** [amzn/selling-partner-api-models#4316]
I noticed I stopped getting financial events data for order created after 1st Nov 2024. I reviewed Seller Api changelog and did not find anything that could cause it. Did I miss something? Anyone else facing this problem?

I am using this operation

`GET /finances/v0/orders/{orderId}/financialEvents
`

described here  https://developer-docs.amazon.com/sp-api/docs/finances-api-reference#listfinancialeventsbyorderid

**Comment by mafge** [comment]
Hi @dsokolowski,
thanks for reaching out!
One possible explanation is that you have been moved to deferred transactions (this happens to every seller on Amazon at some point in time) which means that payments will only be released 7 days after the delivery date of each order. This also affects the Financial Events API because currently the API does not support deferred transactions, but only shows them after they have been released. You should be able to check in Seller Central whether deferred transactions is active for you (there is a Deferred Transactions Report) where you should be able to see your orders from November. Please let me know if this is the case for you! Thanks.
Best,
Marc
Selling Partner Developer Services

**Comment by dsokolowski** [comment]
Thank you for your reply. I think this is not my case though. I have orders older than 7 days that still do not have this info.

**Comment by mafge** [comment]
@dsokolowski @SLMSimplelab If you were able to confirm that deferred transactions is not the case for the behaviour you see, please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end. Thanks!

**Comment by dsokolowski** [comment]
This is what I got from the Amazon support:

> Upon checking our resources, the transaction for the Order #XXX-YYY-ZZZ was Deferred and was released on November 14, 2024.
> The listFinancialEvents operations report only transactions that are released and not deferred. The payments for those events are held until they become release events for security purposes. Once the event becomes a release event, it is processed and provided in the response of the API.
> Since you have requested this listFinancialEvents for this transaction before November 14, 2024 you didn't receive the payload. In this case, I request you to call the listFinancialEvents now for this order #XXX-YYY-ZZZ, you will see the payload properly
>  

I checked my order fetched through api and now financialEvents include shipment events.

**Comment by mafge** [comment]
@dsokolowski Thanks for posting the response here. Please be aware that this behavior applies to all new orders you'll get from now on.

**Comment by tspicer** [comment]
This should not be closed, this amounts to a breaking change to the Finance API

**Comment by SLMSimplelab** [comment]
Yap, the issue should be fixed. I have been waiting for 4 weeks to get the
financial statement with no luck.
