### ISSUE TITLE
[BUG] [SP-API] Create subscription return 403 Unauthorized - Access to requested resource is denied.

### ISSUE THREAD

**Issue by lpongetti** [amzn/selling-partner-api-models#435]
I successfully created the destination and event bridge, but when I run the subscription creation it returns 403:
```
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to requested resource is denied.",
      "details": ""
    }
  ]
}
```

I'm tring to create LISTINGS_ITEM_STATUS_CHANGE subscription.
I have the "Product Listing" role.

the request:
POST https://sellingpartnerapi-eu.amazon.com/notifications/v1/subscriptions/LISTINGS_ITEM_STATUS_CHANGE
{"payloadVersion":"1.0","destinationId":"0b9a0dec-b8bf-4d6f-9f85-fbb0af514566"}

i tried also this request with the same error:
GET https://sellingpartnerapi-eu.amazon.com/notifications/v1/subscriptions/LISTINGS_ITEM_STATUS_CHANGE

Catalog item and listings request works perfectly.

There are other issue related but no one found a reason
https://github.com/amzn/selling-partner-api-models/issues/1001

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
