### ISSUE TITLE
FATAL status || GET_EASYSHIP_DOCUMENTS 

### ISSUE THREAD

**Issue by aprv01** [amzn/selling-partner-api-models#4421]
Request Params
**{
    "reportType": "GET_EASYSHIP_DOCUMENTS",
    "marketplaceIds": [
        "A21TJRUUN4KGV"
    ],
    "dataEndTime": "2024-12-13T16:45:28+00:00",
    "dataStartTime": "2024-12-13T08:30:00+00:00"
}**
-------------Response--------------
**{
    "reportType": "GET_EASYSHIP_DOCUMENTS",
    "processingEndTime": "2024-12-13T10:00:20+00:00",
    "processingStatus": "FATAL",
    "marketplaceIds": [
        "A21TJRUUN4KGV"
    ],
    "reportId": "2995*****070",
    "dataEndTime": "2024-12-13T16:45:28+00:00",
    "createdTime": "2024-12-13T10:00:08+00:00",
    "processingStartTime": "2024-12-13T10:00:14+00:00",
    "dataStartTime": "2024-12-13T08:30:00+00:00"
}**

**Comment by leonardonakagawa** [comment]
Hello @aprv01,

In order to better investigate the issue, we will need more log details for the call made. Could you please [open a support case](https://developer.amazonservices.com/support) with us and share those details?

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
