### ISSUE TITLE
GST B2C MTR Data sync delay

### ISSUE THREAD

**Issue by aprv01** [amzn/selling-partner-api-models#4423]
Why real time data are not syncing.

**Comment by weilinggu** [comment]
Hi @aprv01 ,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

Thanks,
Weiling
Amazon Selling Partner Services
