### ISSUE TITLE
Amazon SP-API fba/inventory/v1/summaries - 403

### ISSUE THREAD

**Issue by lluvia130204** [amzn/selling-partner-api-models#443]
Can someone help me with this problem? when I execute the URL https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries the API gives me the following error:
{
    { "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}

but if I run this URL https://sellingpartnerapi-na.amazon.com/orders/v0/orders with the same token I dont' have issues

@jenilew, @parvathm, @ShivikaK or another dev, could you please help us out here? Thank you!

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
