### ISSUE TITLE
Error response in List Inbound Shipments

### ISSUE THREAD

**Issue by Sasireka2198** [amzn/selling-partner-api-models#444]
I'm calling '/fba/inbound/v0/shipments' api to get list of shipments.

call details:
url:   /fba/inbound/v0/shipments?LastUpdatedAfter=2023-07-12T03:25:26.240348-05:00&LastUpdatedBefore=2023-08-11T03:25:26.307445-05:00&MarketplaceId=A19VAU5U5O7RUS&QueryType=DATE_RANGE

Response:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "At least one of ShipmentStatusList and ShipmentIdList must be provided",
      "details": ""
    }
  ]
}

since I'm using query type as 'DATE_RANGE', only LastUpdatedAfter and LastUpdatedBefore needs to be added to the query parameters. But in response, it is asking me to add ShipmentStatusList and ShipmentIdList. which is odd. 

There was a previous thread (https://github.com/amzn/selling-partner-api-models/issues/888) regarding this issue, but it was closed as fixed. which is clearly not.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
