### ISSUE TITLE
Using the Orders Api

### ISSUE THREAD

**Issue by k4nd1l** [amzn/selling-partner-api-models#445]
Now I am using the getOrders method available in OrdersV0Api.class to get the OrdersList and then the iterate to get Order object which has an optional BuyerInfo according to the https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#orderlist  .
Now this BuyerInfo is null when accessing it . How can i ensure that it is retrieved .

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
