### ISSUE TITLE
[BUG] [SP-API] [getOrders returns empty shipping_address]

### ISSUE THREAD

**Issue by vproogresa** [amzn/selling-partner-api-models#450]
We have a problem receiving orders, they keep coming to us without shipping information, they arrive empty. We already have Amazon's acceptance of the **RDT**.
I am using the private api.
And passing the shippingAddress and also the buyerInfo in data elements.

Since this did not work for me, I tried to retrieve that information through **getreports** with "GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING"
But this time I get an error:
"Exception when calling ReportsV20210630Api->getReports: [403] { "errors": [ { "code": "Unauthorized", "message": "Access to the resource is forbidden", "details": "" } ] }"

I understand that passing the data elements is enough. Or do I have to create a specific configuration to be able to receive the **PII** data.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
