### ISSUE TITLE
Is there a "Send To Amazon" API fix pending, or is the current situation more permanent?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#453]
Is there a "Send To Amazon" API fix pending, or is the current situation more permanent?

Either way this needs to be documented in https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide because currently the situation is bizarre in that API shipments are not easy to view in Seller Central during certain situations.

Once the Shipment ships or arrives, it becomes fairly normal.  But prior to that Seller Central acts like API shipments are something weird that needs to be fixed.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
This is still an open bug that deserves to remain open -- can you convert this to a discussion, since that's where open bugs go now apparently?
