### ISSUE TITLE
Not able to get the final shipping status for each order

### ISSUE THREAD

**Issue by naveenpatnana** [amzn/selling-partner-api-models#455]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

 

## Expected Behavior
The final shipment status for each order beyond 'Shipped', such as 'Out for Delivered', 'Delivered', 'Attempted to Deliver' etc.

 

 

## Current Behavior
We have checked all the below reports and none of them have the final shipment. Is there any report or end point that we should look for?  

 

get_amazon_fulfilled_shipments_data_general
orders
get_flat_file_all_orders_data_by_last_update_general
GET_FLAT_FILE_ALL ORDERS_DATA_BY_ORDER_DATE_GENERAL

**Comment by kpconnell** [comment]
Amazon does not want sellers providing customer service for fulfilment
issues that are FBA.  For FBM you have the tracking and you can track.
Ergo.. there is no valid  use case for this.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
