### ISSUE TITLE
[FEATURE]Add more fields for the GET_PROMOTION_PERFORMANCE_REPORT 

### ISSUE THREAD

**Issue by unstory** [amzn/selling-partner-api-models#466]
I found the GET_PROMOTION_PERFORMANCE_REPORT  miss some important fields compare to the Amazon Seller Center, such as internal description, Committed units, In stock. Can you add this attribute to the GET_PROMOTION_PERFORMANCE_REPORT report?
Thanks and expect your response。

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
