### ISSUE TITLE
[BUG] [SP-API] [Issue] /orders/v0/orders unable to get an order information

### ISSUE THREAD

**Issue by always404** [amzn/selling-partner-api-models#468]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
/orders/v0/orders

## Expected Behavior

Call this interface [/orders/v0/orders] to obtain order information, the order id is **114-7957863-2769800**

## Current Behavior

I can't get the information for this order, but i get this order id from [/finances/v0/financialEventGroups/{evevtGroupId}/financialEvents] evenrResponse.getPayload().getFinancailEvents().getShipmentEventList()

## Context/Screenshots

How do I get order information? My project must get the order details obtained from this interface.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
