### ISSUE TITLE
[BUG] [SP-API] Empty items when get items by "/catalog/2022-04-01/items" with parameter "brandNames"

### ISSUE THREAD

**Issue by catchex** [amzn/selling-partner-api-models#471]
The success response with request parameters:

```shell
curl --location 'https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?marketplaceIds=A2EUQ1WTGCTBG2&keywords=Sports%20%26%20Outdoors&pageSize=20&keywordsLocale=en_US&brandNames=Columbia'  \
--header 'x-amz-access-token: Atza|IwEBILHCzWmzDOq...'
```

The abnormal response with request parameters:

```shell
curl --location 'https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?marketplaceIds=A2EUQ1WTGCTBG2&keywords=Sports%20%26%20Outdoors&pageSize=20&keywordsLocale=en_US&brandNames=Independently%20Published' \
--header 'x-amz-access-token: Atza|IwEBILHCzW...'
```

The brandName is "Columbia" and "Independently%20Published".

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
