### ISSUE TITLE
[BUG] [SP-API] ,the spapi  is still not supported  to add new items ,Is it a bug or intentionally canceling this feature of MWS in updateInboundShipment 

### ISSUE THREAD

**Issue by A-BlackMoon** [amzn/selling-partner-api-models#474]
followed the documentation at: https://docs.developer.amazonservices.com/en_UK/fba_guide/FBAGuide_CreateShipment200Items.html
the MWS can work well 

However , the spapi  is still not supported  to add new items .  

why? it's almost 2024,  the MWS will be deactivated,  dose amazon   will  cancele this feature in the new spapi ??

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
