### ISSUE TITLE
[BUG] [SP-API] [Issue] Api Returns no Data of GET_LEDGER_SUMMARY_VIEW_DATA report

### ISSUE THREAD

**Issue by elishevagithub** [amzn/selling-partner-api-models#489]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
GET_LEDGER_SUMMARY_VIEW_DATA

## Current Behavior
GET_LEDGER_SUMMARY_VIEW_DATA returning empty document with only column names. 
When I look in Amazon, I see that the call is creating a report beginning and ending at 4pm instead of the full day, and I think that's the issue. 
## Context/Screenshots

The report options are using the correct names and the correct time format
"body": {
"reportType": "GET_LEDGER_SUMMARY_VIEW_DATA",
"dataStartTime": "2023-03-01T00:00:00Z",
"dataEndTime": "2023-03-01T23:59:59Z",
"reportOptions": {
"aggregateByLocation":"COUNTRY",
"aggregatedByTimePeriod":"DAILY"
}
}
Any ideas to get Amazon to read the call correctly?

**Comment by shreeharsh-a** [comment]
If you are still facing this issue, please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
