### ISSUE TITLE
[BUG] [SP-API] [Issue] :How to comfirm there is no deferred events in `FinancialEvents` using `listFinancialEvents`

### ISSUE THREAD

**Issue by ljclour** [amzn/selling-partner-api-models#514]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Questions
</code></pre>

## `listFinancialEvents`
when using `listFinancialEvents` path to get some financial data ,in fact it returned a lots, but there is no way to determine if this 
 is complete.

## Expected Behavior
when call this path , I hope to get complete data returned.

## Current Behavior
Using listFinancialEvents , it returned lots. I saved this raw responses into txt files stored with nexttoken.
Sometime it gets 4 to 6 txt files. But after few days or few weeks ,recall with the same paras, finally gets more file then before.
I don't know hot to fix it.

Is this a network problem? or any others caused this?

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
