### ISSUE TITLE
Data Retrieval Issue: buyerName,etc Missing from API Since Feb 21, 2024

### ISSUE THREAD

**Issue by NikaKingLuffy** [amzn/selling-partner-api-models#518]
>  i cant get these data information by request the `orders-api-v0` or `reports-api`, anyone have the similar issue? btw,i can get these data before Feb 21,anyone know y or how to slove this problem?
#### thank you for your reply

**Comment by ouzhiman** [comment]
How did you use reports-api before? I'll try again, which reportType value?
&nbsp;


362155377
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月9日(星期四) 晚上6:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [amzn/selling-partner-api-models] Data Retrieval Issue: buyerName,etc Missing from API Since Feb 21, 2024 (Issue #518)














  
我无法通过请求获取这些数据信息，有人遇到过类似的问题吗？顺便说orders-api-v0一句reports-api，我可以在 2 月 21 日之前获取这些数据，有人知道为什么或如何解决这个问题吗？
  
感谢你的回复
 
—
直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您收到此消息是因为您订阅了该主题。消息ID ：< ***@***.*** &gt;

**Comment by ouzhiman** [comment]
How did you use reports-api before? I'll try again, which reportType value?




362155377
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-models"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[amzn/selling-partner-api-models] Data Retrieval Issue: buyerName,etc Missing from API Since Feb 21, 2024 (Issue #518)





  
i cant get these data information by request the orders-api-v0 or reports-api, anyone have the similar issue? btw,i can get these data before Feb 21,anyone know y or how to slove this problem?
  
thank you for your reply

**Comment by NikaKingLuffy** [comment]
> Hello @NikaKingLuffy,
> 
> On February 19, 2024, we implemented a deprecation of Restricted data required for Tax Remittance in North American marketplaces, as Amazon has taken on the responsibility of calculating and remitting sales tax on behalf of Sellers. It's important to note that the Tax Remittance role should solely be utilized for calculating and remitting sales taxes.
> 
> Alternatively, you can utilize the recipient name attribute provided within the [ShippingAddress](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#address) section.
> 
> The name retrieved from the ShippingAddress (as returned in the orders API response) will consistently represent the name used for shipping purposes, serving as your reliable reference for shipping requirements.
> 
> Previously, the buyer's name was necessary for invoicing purposes. However, since invoicing is no longer necessary, this information is no longer needed.
> 
> Alternatively, the [GET_ORDER_REPORT_DATA_SHIPPING](https://developer-docs.amazon.com/sp-api/docs/order-reports-attributes#get_order_report_data_shipping) report should provide you with the BuyerName if needed.
> 
> Thanks, Chris

I'm sorry to learn from you that the buyerName and other data are no longer available.
Thank you for your reply.
