### ISSUE TITLE
[BUG] GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL does not honor marketplaceId parameter

### ISSUE THREAD

**Issue by Vituli** [amzn/selling-partner-api-models#534]
Describe the bug
If you request through /reports/2021-06-30/reports GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL, and you pass in the amazon.com marketplaceid ATVPDKIKX0DER, you will receive back orders across all of amazon north america, including A1AM78C64UM0Y8 and A2EUQ1WTGCTBG2

**Comment by albert-le-whoop** [comment]
Please fix!!

**Comment by harguph** [comment]
Hello @Vituli ,

Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

Regards
