### ISSUE TITLE
GET to /fba/inbound/v0/shipmentItems  Invalid Input [BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by DestinySolutionspvtltd** [amzn/selling-partner-api-models#537]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
/fba/inbound/v0/shipmentItems
## Expected Behavior

I try to Retrieve Data using Date_Range and it return me Data along with Next token so i try to Retrieve Next data using Next Token but it give me error.

I try all parameter as per Document then also It give same error 
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}

**Comment by harguph** [comment]
Hello @DestinySolutionspvtltd ,

From the error, it seems the request being passed is invalid. Per the API documentation, please ensure "NextToken" is being passed in the query string.

The api [shipmentitems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#get-fbainboundv0shipmentitems) is deprecated.

For continued programmatic access to Fulfillment Inbound, migrate to the [Fulfillment Inbound v2024-03-20 API](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference).

Please reach out to [developer support](https://developer.amazonservices.com/support) if the issue persists so that we can better help you with issues related to SP API.
`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
