### ISSUE TITLE
[Documentation issue or request] [SP-API] What are the available paths and values for JSON_LISTINGS_FEED?

### ISSUE THREAD

**Issue by gyosko** [amzn/selling-partner-api-models#543]
I would like to update some product data using `JSON_LISTINGS_FEED` using a [PatchOperation](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patchoperation) .

Where can I find all the availables paths and values for this type of request?

**Comment by leonardonakagawa** [comment]
Hi @gyosko,

To access the paths to update listings, you can use this flow: [Updating a listings item](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#updating-a-listings-item)

We recommend using the `JSON_LISTINGS_FEED` to patch listings in bulk, when you are doing from 1,500 up to 10,000 item updates per request. Otherwise, Listings Items API will perform better. Check [Should I submit in bulk using the JSON_LISTINGS_FEED or individually with the Listings Items API?](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#should-i-submit-in-bulk-using-the-json_listings_feed-or-individually-with-the-listings-items-api)

Please refer to our documentation [Creating and updating listings items in bulk](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#creating-and-updating-listings-items-in-bulk)


If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
