### ISSUE TITLE
What is the replacement for POST_FLAT_FILE_LISTINGS_DATA ?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#547]
What is the replacement for `POST_FLAT_FILE_LISTINGS_DATA`?

I happened to notice this critical feed is listed on https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations but there's no mention of what replaces it.

**Comment by supoman-service** [comment]
ListingAPI，FeedAPI JSON_LISTING_DATA

johnkw ***@***.***> 于2024年5月9日周四 18:26写道：

**Comment by johnkw** [comment]
`POST_FLAT_FILE_LISTINGS_DATA` is still listed in https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations

https://sellercentral.amazon.com/listing/cards still only has flat file spreadsheets as the download options.  The two Amazon groups don't seem to be talking to each other at all.

**Comment by chapmanjw** [comment]
JSON_LISTINGS_FEED with the Feeds API and the Listings Items APIs are the **only** long-term mechanisms for programmatic submissions of listings data. All other feed formats for listings data (including spreadsheets) are being deprecated in favor of these for **programmatic** use.

We are not eliminating the ability for Seller Central users to submit data via Seller Central in Excel template format. Those are going through their own migration process to use the same underlying data model, etc., that the Listings Items APIs do (just in a spreadsheet format). However, we are no longer supporting spreadsheet uploads programmatically. These are designed to be a human interactive experience, not a programmatic one.

**Comment by johnkw** [comment]
Thanks.  Well it's good to know that at the very least we will be able to programmatically create the feeds and then pass them along for uploading, as a weird fallback solution.

However, it's still concerning that this is marked deprecated when the replacement doesn't exist yet for downloading something in Seller Central for the initial template.  Right now the only workflow/story that makes any sense is:
- download the spreadsheet from Seller Central which contains all of the category node documentation, fields, etc
- save as a TSV for later programmatic editing
- use `POST_FLAT_FILE_LISTINGS_DATA`

I agree with the comment in bug #572 that this workflow is kind of silly or inherently problematic, since there's no way to specify which of the 400+ columns it is that we're actually trying to change.  But until there's a new template to download somewhere, for whatever format the new feeds will require, it's quite concerning to have the current functional workflow be marked deprecated.  I doubt anyone has really even used the new one yet since there's no way to get a template for it.

**Comment by chapmanjw** [comment]
@johnkw We've heard from other developer feedback that a common reason for using spreadsheets from Seller Central in programmatic workflows was that the requirements in the templates were more up-to-date than Category XSDs (which was true as XSD Schema is not fully capable of describing our data requirements). However, with JSON Schemas from the Product Type Definitions API, you get more precise data requirements than what you can extract from templates (while JSON Schema can be quite verbose, it 100% represents all of our rules assigned at the product type level - the only things we can't really represent there are some of the matching rules that depend on what's already in the catalog, which the validation mode of the Listings Items API can help cover before submission). We're also working on designs for alternative representations of these rules (non-JSON Schema) for developers who'd prefer a more bespoke data model for custom integrations rather than using open source libraries, etc., with JSON Schema. 

The other reason we've heard is for editing use-cases, where some would download the category listing report, perform some edits, and upload the updated template. With the Listings Item APIs, those use-cases can be covered by reading the existing SKU data first, modifying the attributes, and submitting either through the Listings Items APIs or JSON_LISTINGS_FEED via the Feeds API. We're also getting ready to launch a "search" operation this year that works similarly to the Catalog Item APIs search operation, which lets you search/paginate/list/etc., SKUs for a seller (or request batches of up-to 20 at a time like the Catalog Items API). 

Aside from these two, are there other reasons that you leverage spreadsheets in your programmatic workflows?

**Comment by johnkw** [comment]
I still can't find any actual replacement for the current workflow.

Let's get extremely specific here. Right now you do:
- go to https://sellercentral.amazon.com/listing/cards/add-product?style=standalone
- type in "stapler"
- download STAPLER.xlsm
- You now have all of the fields that are precisely required, along with a tiny bit of documentation. Fill it out, save, upload via `POST_FLAT_FILE_LISTINGS_DATA` and you're done.  For any future changes you can just programmatically change your TSV file. Easy.

Where is that for JSON?  There's no JSON file download on https://sellercentral.amazon.com/listing/cards/add-product?style=standalone so step 1 is already dead.

If the JSON feed would simply re-use the precisely identical column names as the XLSM/TSV, that would also be easy.  But apparently it does neither of those, instead renaming absolutely everything with no particular pattern to the renames as far as I can tell.

**Comment by johnkw** [comment]
I looked at it. It's not self-documenting like the Excel files are. And the various layers of JSON nesting are rather annoying. It would be much better to have the JSON be a flat list of columns like the Excel/TSV files are.

There's no need for `/definitions/2020-09-01/productTypes` to be part of the API at all. Having it in the API adds no value, and does add lots of confusion.  Rather, there should be a documentation site where you can see the data definitions along with the detailed documentation to go along with each column name.  In Seller Central just add an option to see the documented JSON right next to the link to download the Excel file.

But better yet, avoid the need for any documentation on the JSON at all, by making it a completely flat file with the exact 100% identical column names to the Excel file.  Then there's nothing extra to document and you're done.

**Comment by johnkw** [comment]
This is still a critical bug/issue/whatever.  Please reopen or move this to a discussion until it's fixed?

**Comment by johnkw** [comment]
@MeenaAmz

**Comment by johnkw** [comment]
?

**Comment by johnkw** [comment]
Bug #4318 is the new home of this bug since this one got closed incorrectly.
