### ISSUE TITLE
[BUG] [SP-API] [reports/2021-06-30/reports 500 - internal server Error]

### ISSUE THREAD

**Issue by lubodzia** [amzn/selling-partner-api-models#569]
When I send a request to create a report with a list of categories. I receive an error that tells me nothing. The error message reads, “We encountered an internal error. Try again.", but I don't even know what I'm doing wrong. Please help.

## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Context/Screenshots

Request:
`{
    "reportType": "GET_XML_BROWSE_TREE_DATA",
    "marketplaceIds": [
        "A1C3SOZRARQ6R3"
    ]
}`
Response:
`{
    "errors": [
        {
            "code": "InternalFailure",
            "message": "We encountered an internal error. Please try again.",
            "details": ""
        }
    ]
}`
With StatusCode 500.
x-amzn-RequestId = 4920eb6a-e816-40e9-a3f3-d5289299539d,
X-Amzn-Trace-Id=Root = 1-6638c77e-4920eb6ae81640e9

## Your Environment

Sandbox envorinment. https://sandbox.sellingpartnerapi-eu.amazon.com.

**Comment by leonardonakagawa** [comment]
Hello @lubodzia,

Reports API contains only a static environment to test using Sandbox.

If you check the [model](https://github.com/amzn/selling-partner-api-models/blob/main/models/reports-api-model/reports_2021-06-30.json#L364) you will look the valid reportType to test this operation.

In order to download the `GET_XML_BROWSE_TREE_DATA` I recommend you retrieve it in prod environment.

You can find details regarding this in our [Reports API Use Case guide](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-use-case-guide).

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
