### ISSUE TITLE
Financial extension of permissions

### ISSUE THREAD

**Issue by sugaular** [amzn/selling-partner-api-models#651]
When accessing with FbaInboundApi or DefaultApi, ApiException: (403) is returned.
Perhaps my development account doesn't have permission to access it.
I checked Develop Apps->View profile->Finance and Accounting and pressed Register and it was approved.
Please let me know what else I need to do.

**Comment by sugaular** [comment]
hi shreeharsh-a	
Thank you for your reply	
	
The following are already checked.	
	Product Listing
	Pricing
	Amazon Fulfillment
	Buyer Communication
	Buyer Solicitation
	Selling Partner Insights
	Finance and Accounting
	Inventory and Order Tracking
	Brand Analytics
	
The following was checked and approved 1-2 weeks ago.	
	Finance and Accounting
	Inventory and Order Tracking

**Comment by shreeharsh-a** [comment]
In that case, better to approach developer support so that we can take a closer look at it & help you.

**Comment by sugaular** [comment]
Would you tell me how to contact developer support?

**Comment by harguph** [comment]
please open a [developer support case](https://developer.amazonservices.com/support) sharing the full request and response.

**Comment by liyouzhuo** [comment]
Hello! Can I refer to your online business website design ideas? Because I failed when I applied for brand analysis permission, I was prompted: we require Developers to have an online business website with publicly available, descriptive information about the analytical products and services provided for Amazon Selling Partners. Services and product must be consistent with section 4.4 and 4.5 of our Acceptable Use Policy
