### ISSUE TITLE
Feeds API : getFeed, feeds stay in processingStatus IN_QUEUE

### ISSUE THREAD

**Issue by josamho** [amzn/selling-partner-api-models#657]
Hello, 

We are updating listings items with JSON_LISTINGS_FEED feeds.
For 5 countries with pricing, we make  approximately 1 submission per hour per country. 

BUT for a few days all feeds stay in 'processingStatus' : 'IN_QUEUE' and no one price beeing update.

Is there a problem with this feature? On the SP API STATUS Feeds API is OK....

**Comment by harguph** [comment]
Hello @josamho ,

Thank you for reaching out.

Per the documentation on [Feeds API](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide) 

```
Feeds can take up to eight hours to process

Under high load conditions it is not uncommon for feeds to take up to eight hours to process. Product data feeds are processed sequentially; the most recent feed will be queued in the processing system until previous feed submissions have completed. Substantial processing delays can occur when multiple product feeds contain only a few items each instead of a single product feed with all items.
```

and 
```
If processingStatus is IN_QUEUE or IN_PROGRESS, feed processing is not yet complete. Retry the getFeed operation until processingStatus reaches one of the following terminal states: DONE, CANCELLED, or FATAL.
```

Since it has been a few days post submitting the feed. We would request you to open a [developer support case](https://developer.amazonservices.com/support) and share complete details with the Developer support team so they can assist your further.
